import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

const InputSchema = z.object({
  url: z.string().url().max(2048),
});

type SitemapEntry = { loc: string; lastmod?: string };

async function fetchText(url: string, timeoutMs = 8000): Promise<string | null> {
  try {
    const ctrl = new AbortController();
    const t = setTimeout(() => ctrl.abort(), timeoutMs);
    const r = await fetch(url, {
      signal: ctrl.signal,
      headers: { "User-Agent": "citation.is-llms-txt-generator/1.0 (+https://citation.is)" },
      redirect: "follow",
    });
    clearTimeout(t);
    if (!r.ok) return null;
    return await r.text();
  } catch {
    return null;
  }
}

function parseSitemap(xml: string): { urls: SitemapEntry[]; sitemaps: string[] } {
  const urls: SitemapEntry[] = [];
  const sitemaps: string[] = [];
  const locRe = /<loc>\s*([^<\s]+)\s*<\/loc>(?:[\s\S]*?<lastmod>\s*([^<\s]+)\s*<\/lastmod>)?/gi;
  const isIndex = /<sitemapindex[\s>]/i.test(xml);
  let m: RegExpExecArray | null;
  while ((m = locRe.exec(xml))) {
    if (isIndex) sitemaps.push(m[1]);
    else urls.push({ loc: m[1], lastmod: m[2] });
  }
  return { urls, sitemaps };
}

async function discoverSitemap(origin: string): Promise<string[]> {
  const candidates = [`${origin}/sitemap.xml`, `${origin}/sitemap_index.xml`, `${origin}/sitemap-index.xml`];
  const robots = await fetchText(`${origin}/robots.txt`);
  if (robots) {
    for (const line of robots.split(/\r?\n/)) {
      const m = /^\s*Sitemap:\s*(\S+)/i.exec(line);
      if (m) candidates.unshift(m[1]);
    }
  }
  return Array.from(new Set(candidates));
}

async function collectUrls(startUrls: string[], cap = 300): Promise<SitemapEntry[]> {
  const seen = new Set<string>();
  const out: SitemapEntry[] = [];
  const queue = [...startUrls];
  let hops = 0;
  while (queue.length && out.length < cap && hops < 15) {
    hops++;
    const sm = queue.shift()!;
    if (seen.has(sm)) continue;
    seen.add(sm);
    const xml = await fetchText(sm);
    if (!xml) continue;
    const { urls, sitemaps } = parseSitemap(xml);
    for (const u of urls) {
      if (out.length >= cap) break;
      out.push(u);
    }
    for (const s of sitemaps) if (!seen.has(s)) queue.push(s);
  }
  return out;
}

function titleize(pathname: string): string {
  const seg = pathname.replace(/\/+$/, "").split("/").filter(Boolean).pop() || "Home";
  return seg
    .replace(/[-_]+/g, " ")
    .replace(/\.(html?|php|aspx?)$/i, "")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function categorize(u: URL): string {
  const p = u.pathname.toLowerCase();
  if (p === "/" || p === "") return "Home";
  if (/(^|\/)(blog|posts?|articles?|news)(\/|$)/.test(p)) return "Blog";
  if (/(^|\/)(docs?|documentation|guides?|reference)(\/|$)/.test(p)) return "Docs";
  if (/(^|\/)(product|pricing|features?|solutions?)(\/|$)/.test(p)) return "Product";
  if (/(^|\/)(about|team|company|contact|careers?)(\/|$)/.test(p)) return "Company";
  if (/(^|\/)(api|developer|sdk)(\/|$)/.test(p)) return "Developers";
  return "Other";
}

export const generateLlmsTxt = createServerFn({ method: "POST" })
  .inputValidator((raw) => InputSchema.parse(raw))
  .handler(async ({ data }) => {
    const target = new URL(data.url);
    const origin = `${target.protocol}//${target.host}`;
    const startUrls = await discoverSitemap(origin);
    const entries = await collectUrls(startUrls, 300);

    if (!entries.length) {
      return {
        ok: false as const,
        origin,
        message:
          "No sitemap found. Add /robots.txt with a `Sitemap:` line, or publish /sitemap.xml, then rerun.",
        llmsTxt: "",
        llmsFullPreview: "",
        urlCount: 0,
      };
    }

    const grouped = new Map<string, { title: string; url: string }[]>();
    let host = target.host;
    for (const e of entries) {
      try {
        const u = new URL(e.loc);
        host = u.host;
        const cat = categorize(u);
        const arr = grouped.get(cat) ?? [];
        arr.push({ title: titleize(u.pathname), url: u.toString() });
        grouped.set(cat, arr);
      } catch {
        // skip
      }
    }

    const order = ["Home", "Product", "Docs", "Developers", "Blog", "Company", "Other"];
    const sections = order.filter((k) => grouped.has(k));

    const lines: string[] = [];
    lines.push(`# ${host}`);
    lines.push("");
    lines.push(
      `> Curated index of ${host} for AI agents and LLM crawlers. Generated by citation.is — free, spec-compliant llms.txt.`
    );
    lines.push("");
    for (const s of sections) {
      lines.push(`## ${s}`);
      const items = grouped.get(s)!.slice(0, 40);
      for (const it of items) lines.push(`- [${it.title}](${it.url})`);
      lines.push("");
    }
    lines.push("## Optional");
    lines.push(`- [Sitemap](${startUrls[0]}): Full machine-readable URL list`);
    lines.push("");

    const llmsTxt = lines.join("\n");
    const llmsFullPreview = `# ${host} — llms-full.txt\n\n> Concatenation of the pages listed in llms.txt.\n> Generate by fetching each URL as markdown and joining with clear separators.\n\n(This preview lists ${entries.length} URLs. Run a build step on your side to inline the full markdown.)\n`;

    return {
      ok: true as const,
      origin,
      urlCount: entries.length,
      sections,
      llmsTxt,
      llmsFullPreview,
    };
  });
