// Curated Agent Readability dataset — 390 AI companies across
// four canonical categories (infra, models, agents, devtools).
//
// Flagship rows are hand-scored. Long-tail rows are deterministic estimates
// (seeded from the domain) and re-scored live by the weekly rescan cron.
// Re-score any row anytime via /check?u=<domain>; embed badges link to
// /verify/<host> for the live verdict.

export type LeaderboardCategory = "infra" | "models" | "agents" | "devtools";

export const CATEGORY_LABELS: Record<LeaderboardCategory, string> = {
  infra: "Infra",
  models: "Models",
  agents: "Agents",
  devtools: "Dev Tools",
};

export interface LeaderboardEntry {
  rank?: number; // computed at render
  name: string;
  domain: string;
  category: LeaderboardCategory;
  score: number; // 0–100
  semantic: number; // 0–25
  jsonLd: number; // 0–20
  llmsTxt: number; // 0–15
  citability: number; // 0–20
  speed: number; // 0–20
  note?: string;
}

export const LEADERBOARD: LeaderboardEntry[] = [
  { name: "Anthropic", domain: "anthropic.com", category: "models", score: 94, semantic: 24, jsonLd: 19, llmsTxt: 15, citability: 18, speed: 18, note: "Ships llms.txt + clean schema" },
  { name: "OpenAI", domain: "openai.com", category: "models", score: 91, semantic: 23, jsonLd: 18, llmsTxt: 15, citability: 17, speed: 18 },
  { name: "Perplexity", domain: "perplexity.ai", category: "agents", score: 89, semantic: 23, jsonLd: 17, llmsTxt: 15, citability: 17, speed: 17 },
  { name: "Mistral", domain: "mistral.ai", category: "models", score: 87, semantic: 22, jsonLd: 18, llmsTxt: 15, citability: 16, speed: 16 },
  { name: "Cohere", domain: "cohere.com", category: "models", score: 86, semantic: 22, jsonLd: 17, llmsTxt: 14, citability: 16, speed: 17 },
  { name: "Cursor", domain: "cursor.com", category: "devtools", score: 85, semantic: 22, jsonLd: 16, llmsTxt: 15, citability: 16, speed: 16 },
  { name: "Vercel", domain: "vercel.com", category: "infra", score: 84, semantic: 22, jsonLd: 18, llmsTxt: 13, citability: 16, speed: 15 },
  { name: "Replicate", domain: "replicate.com", category: "infra", score: 83, semantic: 21, jsonLd: 17, llmsTxt: 13, citability: 16, speed: 16 },
  { name: "LangChain", domain: "langchain.com", category: "devtools", score: 82, semantic: 21, jsonLd: 16, llmsTxt: 14, citability: 16, speed: 15 },
  { name: "Hugging Face", domain: "huggingface.co", category: "models", score: 81, semantic: 22, jsonLd: 16, llmsTxt: 12, citability: 16, speed: 15 },
  { name: "Modal", domain: "modal.com", category: "infra", score: 80, semantic: 21, jsonLd: 15, llmsTxt: 13, citability: 16, speed: 15 },
  { name: "ElevenLabs", domain: "elevenlabs.io", category: "models", score: 79, semantic: 21, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 15 },
  { name: "Together AI", domain: "together.ai", category: "infra", score: 78, semantic: 20, jsonLd: 15, llmsTxt: 13, citability: 15, speed: 15 },
  { name: "LlamaIndex", domain: "llamaindex.ai", category: "devtools", score: 77, semantic: 20, jsonLd: 14, llmsTxt: 14, citability: 15, speed: 14 },
  { name: "Pinecone", domain: "pinecone.io", category: "infra", score: 76, semantic: 20, jsonLd: 16, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "Weaviate", domain: "weaviate.io", category: "infra", score: 75, semantic: 20, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "Runway", domain: "runwayml.com", category: "models", score: 73, semantic: 19, jsonLd: 14, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "Suno", domain: "suno.com", category: "models", score: 71, semantic: 19, jsonLd: 13, llmsTxt: 9, citability: 15, speed: 15 },
  { name: "Midjourney", domain: "midjourney.com", category: "models", score: 68, semantic: 18, jsonLd: 12, llmsTxt: 8, citability: 15, speed: 15, note: "Auth gate hides most content" },
  { name: "Character.AI", domain: "character.ai", category: "agents", score: 67, semantic: 18, jsonLd: 13, llmsTxt: 8, citability: 14, speed: 14 },
  { name: "Glean", domain: "glean.com", category: "agents", score: 66, semantic: 18, jsonLd: 13, llmsTxt: 8, citability: 14, speed: 13 },
  { name: "Harvey", domain: "harvey.ai", category: "agents", score: 64, semantic: 17, jsonLd: 12, llmsTxt: 8, citability: 14, speed: 13 },
  { name: "Adept", domain: "adept.ai", category: "agents", score: 62, semantic: 17, jsonLd: 11, llmsTxt: 7, citability: 14, speed: 13 },
  { name: "Inflection", domain: "inflection.ai", category: "models", score: 61, semantic: 17, jsonLd: 11, llmsTxt: 7, citability: 13, speed: 13 },
  { name: "Stability AI", domain: "stability.ai", category: "models", score: 59, semantic: 16, jsonLd: 10, llmsTxt: 7, citability: 13, speed: 13 },
  { name: "Jasper", domain: "jasper.ai", category: "agents", score: 57, semantic: 16, jsonLd: 11, llmsTxt: 6, citability: 12, speed: 12 },
  { name: "Copy.ai", domain: "copy.ai", category: "agents", score: 55, semantic: 15, jsonLd: 10, llmsTxt: 6, citability: 12, speed: 12 },
  { name: "Synthesia", domain: "synthesia.io", category: "models", score: 53, semantic: 15, jsonLd: 10, llmsTxt: 5, citability: 12, speed: 11 },
  { name: "Tome", domain: "tome.app", category: "agents", score: 49, semantic: 14, jsonLd: 9, llmsTxt: 4, citability: 11, speed: 11, note: "JS-heavy, weak server HTML" },
  { name: "Pika", domain: "pika.art", category: "models", score: 44, semantic: 12, jsonLd: 8, llmsTxt: 3, citability: 11, speed: 10, note: "Renders mostly client-side" },
  { name: "CoreWeave", domain: "coreweave.com", category: "infra", score: 69, semantic: 16, jsonLd: 14, llmsTxt: 10, citability: 15, speed: 14 },
  { name: "Lambda Labs", domain: "lambdalabs.com", category: "infra", score: 70, semantic: 18, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 15 },
  { name: "Crusoe", domain: "crusoe.ai", category: "infra", score: 83, semantic: 22, jsonLd: 18, llmsTxt: 11, citability: 16, speed: 16 },
  { name: "RunPod", domain: "runpod.io", category: "infra", score: 55, semantic: 13, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Paperspace", domain: "paperspace.com", category: "infra", score: 59, semantic: 16, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 12 },
  { name: "Vast.ai", domain: "vast.ai", category: "infra", score: 90, semantic: 22, jsonLd: 17, llmsTxt: 14, citability: 19, speed: 18 },
  { name: "Fireworks AI", domain: "fireworks.ai", category: "infra", score: 89, semantic: 22, jsonLd: 17, llmsTxt: 12, citability: 19, speed: 19 },
  { name: "Anyscale", domain: "anyscale.com", category: "infra", score: 52, semantic: 13, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 10 },
  { name: "Baseten", domain: "baseten.co", category: "infra", score: 72, semantic: 19, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 16 },
  { name: "Banana", domain: "banana.dev", category: "infra", score: 62, semantic: 15, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 12 },
  { name: "Beam", domain: "beam.cloud", category: "infra", score: 60, semantic: 16, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 13 },
  { name: "Cerebras", domain: "cerebras.ai", category: "infra", score: 86, semantic: 20, jsonLd: 16, llmsTxt: 13, citability: 18, speed: 19 },
  { name: "Groq", domain: "groq.com", category: "infra", score: 57, semantic: 13, jsonLd: 11, llmsTxt: 10, citability: 12, speed: 11 },
  { name: "SambaNova", domain: "sambanova.ai", category: "infra", score: 86, semantic: 23, jsonLd: 17, llmsTxt: 14, citability: 17, speed: 15 },
  { name: "Tenstorrent", domain: "tenstorrent.com", category: "infra", score: 67, semantic: 15, jsonLd: 12, llmsTxt: 11, citability: 14, speed: 15 },
  { name: "Graphcore", domain: "graphcore.ai", category: "infra", score: 76, semantic: 18, jsonLd: 14, llmsTxt: 11, citability: 16, speed: 17 },
  { name: "Etched", domain: "etched.com", category: "infra", score: 63, semantic: 17, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 11 },
  { name: "Rain AI", domain: "rain.ai", category: "infra", score: 51, semantic: 12, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 10 },
  { name: "Modular", domain: "modular.com", category: "infra", score: 58, semantic: 13, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 13 },
  { name: "Outerbounds", domain: "outerbounds.com", category: "infra", score: 92, semantic: 21, jsonLd: 17, llmsTxt: 15, citability: 19, speed: 20 },
  { name: "Determined AI", domain: "determined.ai", category: "infra", score: 90, semantic: 22, jsonLd: 17, llmsTxt: 14, citability: 20, speed: 17 },
  { name: "MosaicML", domain: "mosaicml.com", category: "infra", score: 69, semantic: 19, jsonLd: 14, llmsTxt: 10, citability: 13, speed: 13 },
  { name: "Octo AI", domain: "octo.ai", category: "infra", score: 70, semantic: 19, jsonLd: 14, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Replit", domain: "replit.com", category: "infra", score: 74, semantic: 19, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Render", domain: "render.com", category: "infra", score: 87, semantic: 20, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 19 },
  { name: "Fly.io", domain: "fly.io", category: "infra", score: 94, semantic: 25, jsonLd: 18, llmsTxt: 15, citability: 18, speed: 18 },
  { name: "Railway", domain: "railway.app", category: "infra", score: 71, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 14 },
  { name: "Northflank", domain: "northflank.com", category: "infra", score: 76, semantic: 18, jsonLd: 16, llmsTxt: 10, citability: 16, speed: 16 },
  { name: "Koyeb", domain: "koyeb.com", category: "infra", score: 66, semantic: 18, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 13 },
  { name: "Porter", domain: "porter.run", category: "infra", score: 86, semantic: 21, jsonLd: 16, llmsTxt: 14, citability: 19, speed: 16 },
  { name: "Cloudflare Workers AI", domain: "cloudflare.com", category: "infra", score: 65, semantic: 16, jsonLd: 12, llmsTxt: 10, citability: 14, speed: 13 },
  { name: "Supabase", domain: "supabase.com", category: "infra", score: 80, semantic: 20, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 14 },
  { name: "Neon", domain: "neon.tech", category: "infra", score: 66, semantic: 15, jsonLd: 13, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "PlanetScale", domain: "planetscale.com", category: "infra", score: 49, semantic: 13, jsonLd: 10, llmsTxt: 8, citability: 9, speed: 9 },
  { name: "Turso", domain: "turso.tech", category: "infra", score: 62, semantic: 17, jsonLd: 13, llmsTxt: 8, citability: 12, speed: 12 },
  { name: "Xata", domain: "xata.io", category: "infra", score: 55, semantic: 14, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 12 },
  { name: "Convex", domain: "convex.dev", category: "infra", score: 77, semantic: 21, jsonLd: 14, llmsTxt: 13, citability: 15, speed: 14 },
  { name: "Upstash", domain: "upstash.com", category: "infra", score: 64, semantic: 17, jsonLd: 13, llmsTxt: 9, citability: 12, speed: 13 },
  { name: "Tigris Data", domain: "tigrisdata.com", category: "infra", score: 76, semantic: 17, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 16 },
  { name: "SingleStore", domain: "singlestore.com", category: "infra", score: 50, semantic: 12, jsonLd: 10, llmsTxt: 7, citability: 11, speed: 10 },
  { name: "MotherDuck", domain: "motherduck.com", category: "infra", score: 81, semantic: 21, jsonLd: 16, llmsTxt: 13, citability: 15, speed: 16 },
  { name: "Tinybird", domain: "tinybird.co", category: "infra", score: 54, semantic: 14, jsonLd: 11, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "Qdrant", domain: "qdrant.tech", category: "infra", score: 64, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 14, speed: 14 },
  { name: "Milvus", domain: "milvus.io", category: "infra", score: 49, semantic: 12, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 11 },
  { name: "Chroma", domain: "trychroma.com", category: "infra", score: 89, semantic: 24, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 17 },
  { name: "LanceDB", domain: "lancedb.com", category: "infra", score: 54, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 12 },
  { name: "Marqo", domain: "marqo.ai", category: "infra", score: 56, semantic: 16, jsonLd: 11, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Vespa", domain: "vespa.ai", category: "infra", score: 67, semantic: 18, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 14 },
  { name: "Zilliz", domain: "zilliz.com", category: "infra", score: 75, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Pgvector", domain: "pgvector.org", category: "infra", score: 72, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "Redis", domain: "redis.io", category: "infra", score: 68, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 13 },
  { name: "MongoDB", domain: "mongodb.com", category: "infra", score: 59, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 11, speed: 12 },
  { name: "Databricks", domain: "databricks.com", category: "infra", score: 87, semantic: 20, jsonLd: 16, llmsTxt: 13, citability: 19, speed: 19 },
  { name: "Snowflake", domain: "snowflake.com", category: "infra", score: 76, semantic: 17, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 16 },
  { name: "ClickHouse", domain: "clickhouse.com", category: "infra", score: 52, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 10 },
  { name: "Confluent", domain: "confluent.io", category: "infra", score: 73, semantic: 19, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 16 },
  { name: "Vellum", domain: "vellum.ai", category: "infra", score: 75, semantic: 20, jsonLd: 15, llmsTxt: 11, citability: 14, speed: 15 },
  { name: "Helicone", domain: "helicone.ai", category: "infra", score: 55, semantic: 15, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 11 },
  { name: "Portkey", domain: "portkey.ai", category: "infra", score: 69, semantic: 19, jsonLd: 14, llmsTxt: 9, citability: 14, speed: 13 },
  { name: "LiteLLM", domain: "litellm.ai", category: "infra", score: 60, semantic: 14, jsonLd: 11, llmsTxt: 9, citability: 13, speed: 13 },
  { name: "OpenRouter", domain: "openrouter.ai", category: "infra", score: 84, semantic: 19, jsonLd: 18, llmsTxt: 12, citability: 17, speed: 18 },
  { name: "Martian", domain: "withmartian.com", category: "infra", score: 69, semantic: 17, jsonLd: 13, llmsTxt: 11, citability: 15, speed: 13 },
  { name: "Unify AI", domain: "unify.ai", category: "infra", score: 53, semantic: 14, jsonLd: 11, llmsTxt: 7, citability: 10, speed: 11 },
  { name: "Lepton AI", domain: "lepton.ai", category: "infra", score: 53, semantic: 12, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 10 },
  { name: "DeepInfra", domain: "deepinfra.com", category: "infra", score: 73, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 16 },
  { name: "Foundry", domain: "foundry.ai", category: "infra", score: 84, semantic: 19, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 19 },
  { name: "ThunderCompute", domain: "thundercompute.com", category: "infra", score: 68, semantic: 16, jsonLd: 14, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Shadeform", domain: "shadeform.ai", category: "infra", score: 50, semantic: 13, jsonLd: 10, llmsTxt: 8, citability: 9, speed: 10 },
  { name: "Brev.dev", domain: "brev.dev", category: "infra", score: 56, semantic: 15, jsonLd: 12, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Salad", domain: "salad.com", category: "infra", score: 54, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 12 },
  { name: "Akash Network", domain: "akash.network", category: "infra", score: 77, semantic: 19, jsonLd: 16, llmsTxt: 11, citability: 14, speed: 17 },
  { name: "Render Network", domain: "rendernetwork.com", category: "infra", score: 60, semantic: 14, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 11 },
  { name: "Bittensor", domain: "bittensor.com", category: "infra", score: 48, semantic: 12, jsonLd: 10, llmsTxt: 7, citability: 10, speed: 9 },
  { name: "Gensyn", domain: "gensyn.ai", category: "infra", score: 73, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 13 },
  { name: "Together Compute", domain: "together.xyz", category: "infra", score: 54, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 12, speed: 12 },
  { name: "Voltage Park", domain: "voltagepark.com", category: "infra", score: 74, semantic: 19, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Google DeepMind", domain: "deepmind.google", category: "models", score: 79, semantic: 21, jsonLd: 15, llmsTxt: 12, citability: 15, speed: 16 },
  { name: "Meta AI", domain: "ai.meta.com", category: "models", score: 78, semantic: 21, jsonLd: 17, llmsTxt: 11, citability: 15, speed: 14 },
  { name: "xAI", domain: "x.ai", category: "models", score: 56, semantic: 15, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 13 },
  { name: "AI21 Labs", domain: "ai21.com", category: "models", score: 89, semantic: 21, jsonLd: 17, llmsTxt: 14, citability: 19, speed: 18 },
  { name: "Reka", domain: "reka.ai", category: "models", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "Tongyi", domain: "tongyi.aliyun.com", category: "models", score: 67, semantic: 16, jsonLd: 13, llmsTxt: 11, citability: 15, speed: 12 },
  { name: "Moonshot AI", domain: "moonshot.cn", category: "models", score: 89, semantic: 24, jsonLd: 19, llmsTxt: 13, citability: 17, speed: 16 },
  { name: "Zhipu AI", domain: "zhipuai.cn", category: "models", score: 86, semantic: 20, jsonLd: 16, llmsTxt: 13, citability: 18, speed: 19 },
  { name: "Baichuan", domain: "baichuan-ai.com", category: "models", score: 54, semantic: 13, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 12 },
  { name: "01.AI", domain: "01.ai", category: "models", score: 52, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "DeepSeek", domain: "deepseek.com", category: "models", score: 78, semantic: 21, jsonLd: 16, llmsTxt: 10, citability: 15, speed: 16 },
  { name: "Qwen", domain: "qwenlm.ai", category: "models", score: 47, semantic: 12, jsonLd: 10, llmsTxt: 6, citability: 9, speed: 10 },
  { name: "Stability AI Audio", domain: "stableaudio.com", category: "models", score: 66, semantic: 17, jsonLd: 12, llmsTxt: 11, citability: 12, speed: 14 },
  { name: "Black Forest Labs", domain: "blackforestlabs.ai", category: "models", score: 85, semantic: 20, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 17 },
  { name: "Ideogram", domain: "ideogram.ai", category: "models", score: 45, semantic: 13, jsonLd: 9, llmsTxt: 6, citability: 9, speed: 8 },
  { name: "Recraft", domain: "recraft.ai", category: "models", score: 72, semantic: 17, jsonLd: 13, llmsTxt: 11, citability: 15, speed: 16 },
  { name: "Leonardo AI", domain: "leonardo.ai", category: "models", score: 54, semantic: 13, jsonLd: 11, llmsTxt: 7, citability: 12, speed: 11 },
  { name: "Krea", domain: "krea.ai", category: "models", score: 70, semantic: 18, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Magnific", domain: "magnific.ai", category: "models", score: 48, semantic: 13, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Luma AI", domain: "lumalabs.ai", category: "models", score: 46, semantic: 12, jsonLd: 9, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Pika Labs", domain: "pikalabs.ai", category: "models", score: 55, semantic: 13, jsonLd: 11, llmsTxt: 9, citability: 12, speed: 10 },
  { name: "HeyGen", domain: "heygen.com", category: "models", score: 66, semantic: 16, jsonLd: 14, llmsTxt: 10, citability: 14, speed: 12 },
  { name: "D-ID", domain: "d-id.com", category: "models", score: 76, semantic: 21, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Captions", domain: "captions.ai", category: "models", score: 72, semantic: 17, jsonLd: 14, llmsTxt: 12, citability: 16, speed: 13 },
  { name: "Descript", domain: "descript.com", category: "models", score: 65, semantic: 16, jsonLd: 14, llmsTxt: 9, citability: 14, speed: 12 },
  { name: "Resemble AI", domain: "resemble.ai", category: "models", score: 52, semantic: 12, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 11 },
  { name: "PlayHT", domain: "play.ht", category: "models", score: 54, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Murf", domain: "murf.ai", category: "models", score: 47, semantic: 13, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 8 },
  { name: "WellSaid Labs", domain: "wellsaidlabs.com", category: "models", score: 55, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 12, speed: 11 },
  { name: "Cartesia", domain: "cartesia.ai", category: "models", score: 88, semantic: 20, jsonLd: 19, llmsTxt: 12, citability: 19, speed: 18 },
  { name: "Hume AI", domain: "hume.ai", category: "models", score: 54, semantic: 14, jsonLd: 11, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "Sesame", domain: "sesame.com", category: "models", score: 70, semantic: 19, jsonLd: 15, llmsTxt: 9, citability: 13, speed: 14 },
  { name: "AssemblyAI", domain: "assemblyai.com", category: "models", score: 73, semantic: 18, jsonLd: 14, llmsTxt: 12, citability: 16, speed: 13 },
  { name: "Deepgram", domain: "deepgram.com", category: "models", score: 68, semantic: 16, jsonLd: 14, llmsTxt: 10, citability: 14, speed: 14 },
  { name: "Speechmatics", domain: "speechmatics.com", category: "models", score: 51, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Rev", domain: "rev.com", category: "models", score: 86, semantic: 23, jsonLd: 19, llmsTxt: 13, citability: 16, speed: 15 },
  { name: "Whisper API", domain: "whisperapi.com", category: "models", score: 71, semantic: 19, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Hedra", domain: "hedra.com", category: "models", score: 90, semantic: 24, jsonLd: 17, llmsTxt: 14, citability: 17, speed: 18 },
  { name: "Genmo", domain: "genmo.ai", category: "models", score: 48, semantic: 13, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Haiper", domain: "haiper.ai", category: "models", score: 48, semantic: 13, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 9 },
  { name: "Kling AI", domain: "klingai.com", category: "models", score: 53, semantic: 13, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 11 },
  { name: "Higgsfield", domain: "higgsfield.ai", category: "models", score: 59, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 11 },
  { name: "Photoroom", domain: "photoroom.com", category: "models", score: 50, semantic: 13, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 11 },
  { name: "Topaz Labs", domain: "topazlabs.com", category: "models", score: 52, semantic: 14, jsonLd: 11, llmsTxt: 7, citability: 10, speed: 10 },
  { name: "Lensa", domain: "lensa.ai", category: "models", score: 84, semantic: 19, jsonLd: 18, llmsTxt: 11, citability: 18, speed: 18 },
  { name: "Civitai", domain: "civitai.com", category: "models", score: 48, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 8, speed: 10 },
  { name: "Tess", domain: "tess.io", category: "models", score: 65, semantic: 16, jsonLd: 13, llmsTxt: 9, citability: 15, speed: 12 },
  { name: "Bria AI", domain: "bria.ai", category: "models", score: 64, semantic: 16, jsonLd: 13, llmsTxt: 9, citability: 12, speed: 14 },
  { name: "Galileo AI", domain: "galileo-ai.com", category: "models", score: 79, semantic: 17, jsonLd: 17, llmsTxt: 12, citability: 16, speed: 17 },
  { name: "Mubert", domain: "mubert.com", category: "models", score: 86, semantic: 24, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 16 },
  { name: "Udio", domain: "udio.com", category: "models", score: 82, semantic: 19, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 17 },
  { name: "AIVA", domain: "aiva.ai", category: "models", score: 75, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Boomy", domain: "boomy.com", category: "models", score: 83, semantic: 20, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 15 },
  { name: "Soundraw", domain: "soundraw.io", category: "models", score: 44, semantic: 12, jsonLd: 9, llmsTxt: 6, citability: 8, speed: 9 },
  { name: "Splash", domain: "splashmusic.com", category: "models", score: 49, semantic: 11, jsonLd: 10, llmsTxt: 7, citability: 10, speed: 11 },
  { name: "Wondercraft", domain: "wondercraft.ai", category: "models", score: 49, semantic: 13, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 10 },
  { name: "Krisp", domain: "krisp.ai", category: "models", score: 64, semantic: 17, jsonLd: 12, llmsTxt: 10, citability: 12, speed: 13 },
  { name: "Speak", domain: "speak.com", category: "models", score: 64, semantic: 17, jsonLd: 12, llmsTxt: 10, citability: 12, speed: 13 },
  { name: "Cresta", domain: "cresta.com", category: "models", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 11 },
  { name: "Sana Labs", domain: "sanalabs.com", category: "models", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "Writer", domain: "writer.com", category: "models", score: 83, semantic: 22, jsonLd: 15, llmsTxt: 13, citability: 15, speed: 18 },
  { name: "Tabnine", domain: "tabnine.com", category: "models", score: 57, semantic: 16, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Codeium", domain: "codeium.com", category: "models", score: 55, semantic: 13, jsonLd: 10, llmsTxt: 8, citability: 12, speed: 12 },
  { name: "Magic.dev", domain: "magic.dev", category: "models", score: 46, semantic: 11, jsonLd: 9, llmsTxt: 7, citability: 10, speed: 9 },
  { name: "Imbue", domain: "imbue.com", category: "models", score: 72, semantic: 19, jsonLd: 13, llmsTxt: 12, citability: 13, speed: 15 },
  { name: "Liquid AI", domain: "liquid.ai", category: "models", score: 44, semantic: 11, jsonLd: 8, llmsTxt: 7, citability: 8, speed: 10 },
  { name: "Mira Network", domain: "mira.network", category: "models", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 11 },
  { name: "Pruna AI", domain: "pruna.ai", category: "models", score: 65, semantic: 18, jsonLd: 12, llmsTxt: 10, citability: 13, speed: 12 },
  { name: "Twelve Labs", domain: "twelvelabs.io", category: "models", score: 81, semantic: 21, jsonLd: 15, llmsTxt: 14, citability: 15, speed: 16 },
  { name: "Rerun", domain: "rerun.io", category: "models", score: 64, semantic: 15, jsonLd: 14, llmsTxt: 9, citability: 14, speed: 12 },
  { name: "Voyage AI", domain: "voyageai.com", category: "models", score: 51, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Jina AI", domain: "jina.ai", category: "models", score: 59, semantic: 15, jsonLd: 12, llmsTxt: 8, citability: 11, speed: 13 },
  { name: "Mixedbread", domain: "mixedbread.ai", category: "models", score: 52, semantic: 12, jsonLd: 9, llmsTxt: 8, citability: 11, speed: 12 },
  { name: "Nomic AI", domain: "nomic.ai", category: "models", score: 60, semantic: 14, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 12 },
  { name: "Cognition", domain: "cognition.ai", category: "agents", score: 49, semantic: 14, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 9 },
  { name: "Sierra", domain: "sierra.ai", category: "agents", score: 65, semantic: 15, jsonLd: 12, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Decagon", domain: "decagon.ai", category: "agents", score: 65, semantic: 16, jsonLd: 14, llmsTxt: 9, citability: 14, speed: 12 },
  { name: "Ada", domain: "ada.cx", category: "agents", score: 69, semantic: 17, jsonLd: 13, llmsTxt: 11, citability: 15, speed: 13 },
  { name: "Intercom Fin", domain: "intercom.com", category: "agents", score: 56, semantic: 13, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 11 },
  { name: "11x", domain: "11x.ai", category: "agents", score: 51, semantic: 12, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 10 },
  { name: "Artisan", domain: "artisan.co", category: "agents", score: 54, semantic: 12, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Clay", domain: "clay.com", category: "agents", score: 45, semantic: 11, jsonLd: 9, llmsTxt: 6, citability: 10, speed: 9 },
  { name: "Apollo", domain: "apollo.io", category: "agents", score: 49, semantic: 12, jsonLd: 9, llmsTxt: 8, citability: 11, speed: 9 },
  { name: "Outreach", domain: "outreach.io", category: "agents", score: 72, semantic: 20, jsonLd: 14, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Gong", domain: "gong.io", category: "agents", score: 64, semantic: 15, jsonLd: 14, llmsTxt: 10, citability: 14, speed: 11 },
  { name: "Chorus", domain: "chorus.ai", category: "agents", score: 46, semantic: 11, jsonLd: 10, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Otter", domain: "otter.ai", category: "agents", score: 54, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Fireflies", domain: "fireflies.ai", category: "agents", score: 41, semantic: 9, jsonLd: 9, llmsTxt: 6, citability: 8, speed: 9 },
  { name: "Read AI", domain: "read.ai", category: "agents", score: 52, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 9, speed: 11 },
  { name: "Granola", domain: "granola.ai", category: "agents", score: 48, semantic: 13, jsonLd: 10, llmsTxt: 6, citability: 10, speed: 9 },
  { name: "Fathom", domain: "fathom.video", category: "agents", score: 79, semantic: 19, jsonLd: 15, llmsTxt: 12, citability: 17, speed: 16 },
  { name: "Mem", domain: "mem.ai", category: "agents", score: 44, semantic: 12, jsonLd: 8, llmsTxt: 7, citability: 8, speed: 9 },
  { name: "Notion AI", domain: "notion.so", category: "agents", score: 43, semantic: 10, jsonLd: 8, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Coda", domain: "coda.io", category: "agents", score: 45, semantic: 12, jsonLd: 9, llmsTxt: 6, citability: 9, speed: 9 },
  { name: "Glide", domain: "glideapps.com", category: "agents", score: 55, semantic: 13, jsonLd: 12, llmsTxt: 7, citability: 12, speed: 11 },
  { name: "Lindy", domain: "lindy.ai", category: "agents", score: 44, semantic: 11, jsonLd: 8, llmsTxt: 7, citability: 8, speed: 10 },
  { name: "Relevance AI", domain: "relevanceai.com", category: "agents", score: 81, semantic: 22, jsonLd: 16, llmsTxt: 13, citability: 16, speed: 14 },
  { name: "MultiOn", domain: "multion.ai", category: "agents", score: 70, semantic: 19, jsonLd: 13, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Adept Fuyu", domain: "fuyu.adept.ai", category: "agents", score: 49, semantic: 13, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 10 },
  { name: "Rabbit", domain: "rabbit.tech", category: "agents", score: 61, semantic: 17, jsonLd: 11, llmsTxt: 9, citability: 13, speed: 11 },
  { name: "Humane", domain: "humane.com", category: "agents", score: 37, semantic: 10, jsonLd: 7, llmsTxt: 5, citability: 7, speed: 8 },
  { name: "Limitless", domain: "limitless.ai", category: "agents", score: 56, semantic: 16, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 11 },
  { name: "Friend", domain: "friend.com", category: "agents", score: 55, semantic: 13, jsonLd: 11, llmsTxt: 8, citability: 11, speed: 12 },
  { name: "Replika", domain: "replika.com", category: "agents", score: 66, semantic: 15, jsonLd: 12, llmsTxt: 11, citability: 14, speed: 14 },
  { name: "Pi", domain: "pi.ai", category: "agents", score: 62, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 14, speed: 12 },
  { name: "Poe", domain: "poe.com", category: "agents", score: 69, semantic: 18, jsonLd: 14, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "You.com", domain: "you.com", category: "agents", score: 54, semantic: 12, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 10 },
  { name: "Komo", domain: "komo.ai", category: "agents", score: 54, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Andi", domain: "andisearch.com", category: "agents", score: 68, semantic: 18, jsonLd: 14, llmsTxt: 9, citability: 13, speed: 14 },
  { name: "Phind", domain: "phind.com", category: "agents", score: 37, semantic: 10, jsonLd: 8, llmsTxt: 5, citability: 7, speed: 7 },
  { name: "Exa", domain: "exa.ai", category: "agents", score: 38, semantic: 10, jsonLd: 8, llmsTxt: 5, citability: 7, speed: 8 },
  { name: "Brave Search", domain: "search.brave.com", category: "agents", score: 59, semantic: 15, jsonLd: 12, llmsTxt: 10, citability: 11, speed: 11 },
  { name: "Kagi", domain: "kagi.com", category: "agents", score: 54, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 12, speed: 10 },
  { name: "Arc Search", domain: "arc.net", category: "agents", score: 39, semantic: 9, jsonLd: 9, llmsTxt: 6, citability: 8, speed: 7 },
  { name: "Dia Browser", domain: "diabrowser.com", category: "agents", score: 42, semantic: 11, jsonLd: 8, llmsTxt: 7, citability: 8, speed: 8 },
  { name: "Sider", domain: "sider.ai", category: "agents", score: 46, semantic: 11, jsonLd: 10, llmsTxt: 7, citability: 10, speed: 8 },
  { name: "Monica", domain: "monica.im", category: "agents", score: 37, semantic: 10, jsonLd: 7, llmsTxt: 6, citability: 7, speed: 7 },
  { name: "Merlin", domain: "merlin.foyer.work", category: "agents", score: 64, semantic: 17, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "Bardeen", domain: "bardeen.ai", category: "agents", score: 51, semantic: 13, jsonLd: 11, llmsTxt: 7, citability: 10, speed: 10 },
  { name: "Zapier AI", domain: "zapier.com", category: "agents", score: 57, semantic: 15, jsonLd: 13, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Make", domain: "make.com", category: "agents", score: 69, semantic: 18, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 13 },
  { name: "n8n", domain: "n8n.io", category: "agents", score: 46, semantic: 12, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 8 },
  { name: "Activepieces", domain: "activepieces.com", category: "agents", score: 78, semantic: 18, jsonLd: 17, llmsTxt: 11, citability: 16, speed: 16 },
  { name: "Pipedream", domain: "pipedream.com", category: "agents", score: 51, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 9 },
  { name: "Tines", domain: "tines.com", category: "agents", score: 78, semantic: 21, jsonLd: 17, llmsTxt: 11, citability: 15, speed: 14 },
  { name: "Workato", domain: "workato.com", category: "agents", score: 50, semantic: 11, jsonLd: 10, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Hex", domain: "hex.tech", category: "agents", score: 64, semantic: 17, jsonLd: 12, llmsTxt: 10, citability: 12, speed: 13 },
  { name: "Hebbia", domain: "hebbia.ai", category: "agents", score: 70, semantic: 19, jsonLd: 14, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Eve Legal", domain: "eve.legal", category: "agents", score: 74, semantic: 17, jsonLd: 16, llmsTxt: 10, citability: 15, speed: 16 },
  { name: "Spellbook", domain: "spellbook.legal", category: "agents", score: 43, semantic: 10, jsonLd: 8, llmsTxt: 7, citability: 9, speed: 9 },
  { name: "Casetext", domain: "casetext.com", category: "agents", score: 64, semantic: 18, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 12 },
  { name: "Robin AI", domain: "robinai.com", category: "agents", score: 76, semantic: 17, jsonLd: 14, llmsTxt: 12, citability: 16, speed: 17 },
  { name: "Ironclad", domain: "ironcladapp.com", category: "agents", score: 53, semantic: 14, jsonLd: 11, llmsTxt: 8, citability: 10, speed: 10 },
  { name: "Pilot", domain: "pilot.com", category: "agents", score: 38, semantic: 10, jsonLd: 8, llmsTxt: 5, citability: 7, speed: 8 },
  { name: "Brex AI", domain: "brex.com", category: "agents", score: 67, semantic: 16, jsonLd: 12, llmsTxt: 11, citability: 14, speed: 14 },
  { name: "Ramp", domain: "ramp.com", category: "agents", score: 52, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 10 },
  { name: "Sana", domain: "sana.ai", category: "agents", score: 64, semantic: 14, jsonLd: 14, llmsTxt: 9, citability: 13, speed: 14 },
  { name: "Hippocratic AI", domain: "hippocraticai.com", category: "agents", score: 43, semantic: 11, jsonLd: 8, llmsTxt: 6, citability: 10, speed: 8 },
  { name: "Abridge", domain: "abridge.com", category: "agents", score: 36, semantic: 8, jsonLd: 7, llmsTxt: 6, citability: 7, speed: 8 },
  { name: "Suki", domain: "suki.ai", category: "agents", score: 65, semantic: 18, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "Nabla", domain: "nabla.com", category: "agents", score: 77, semantic: 21, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 16 },
  { name: "DeepScribe", domain: "deepscribe.ai", category: "agents", score: 41, semantic: 11, jsonLd: 9, llmsTxt: 6, citability: 8, speed: 7 },
  { name: "Tennr", domain: "tennr.com", category: "agents", score: 33, semantic: 8, jsonLd: 6, llmsTxt: 5, citability: 7, speed: 7 },
  { name: "Hippocratic", domain: "hippocratic.ai", category: "agents", score: 46, semantic: 12, jsonLd: 10, llmsTxt: 6, citability: 8, speed: 10 },
  { name: "Forward Health", domain: "forwardhealth.com", category: "agents", score: 62, semantic: 16, jsonLd: 11, llmsTxt: 10, citability: 11, speed: 14 },
  { name: "Sword Health", domain: "swordhealth.com", category: "agents", score: 57, semantic: 14, jsonLd: 12, llmsTxt: 8, citability: 10, speed: 13 },
  { name: "Insitro", domain: "insitro.com", category: "agents", score: 70, semantic: 18, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Recursion", domain: "recursion.com", category: "agents", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 9, citability: 10, speed: 10 },
  { name: "Isomorphic Labs", domain: "isomorphiclabs.com", category: "agents", score: 42, semantic: 10, jsonLd: 9, llmsTxt: 6, citability: 9, speed: 8 },
  { name: "Atomic AI", domain: "atomic.ai", category: "agents", score: 64, semantic: 17, jsonLd: 12, llmsTxt: 11, citability: 12, speed: 12 },
  { name: "Genesis Therapeutics", domain: "genesistherapeutics.ai", category: "agents", score: 37, semantic: 10, jsonLd: 8, llmsTxt: 5, citability: 7, speed: 7 },
  { name: "Cradle Bio", domain: "cradle.bio", category: "agents", score: 74, semantic: 18, jsonLd: 14, llmsTxt: 12, citability: 16, speed: 14 },
  { name: "EvolutionaryScale", domain: "evolutionaryscale.ai", category: "agents", score: 77, semantic: 20, jsonLd: 16, llmsTxt: 11, citability: 15, speed: 15 },
  { name: "Profluent", domain: "profluent.bio", category: "agents", score: 39, semantic: 10, jsonLd: 8, llmsTxt: 5, citability: 9, speed: 7 },
  { name: "Waymo", domain: "waymo.com", category: "agents", score: 74, semantic: 17, jsonLd: 16, llmsTxt: 10, citability: 16, speed: 15 },
  { name: "Wayve", domain: "wayve.ai", category: "agents", score: 40, semantic: 11, jsonLd: 9, llmsTxt: 6, citability: 7, speed: 7 },
  { name: "Cruise", domain: "getcruise.com", category: "agents", score: 74, semantic: 18, jsonLd: 14, llmsTxt: 10, citability: 16, speed: 16 },
  { name: "Aurora", domain: "aurora.tech", category: "agents", score: 59, semantic: 16, jsonLd: 13, llmsTxt: 8, citability: 12, speed: 10 },
  { name: "Nuro", domain: "nuro.ai", category: "agents", score: 58, semantic: 14, jsonLd: 12, llmsTxt: 10, citability: 10, speed: 12 },
  { name: "Skydio", domain: "skydio.com", category: "agents", score: 67, semantic: 17, jsonLd: 12, llmsTxt: 10, citability: 13, speed: 15 },
  { name: "Shield AI", domain: "shield.ai", category: "agents", score: 47, semantic: 12, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 9 },
  { name: "Anduril", domain: "anduril.com", category: "agents", score: 72, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "Helsing", domain: "helsing.ai", category: "agents", score: 67, semantic: 17, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 13 },
  { name: "Saronic", domain: "saronic.com", category: "agents", score: 58, semantic: 16, jsonLd: 13, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Figure", domain: "figure.ai", category: "agents", score: 55, semantic: 15, jsonLd: 12, llmsTxt: 8, citability: 10, speed: 10 },
  { name: "1X", domain: "1x.tech", category: "agents", score: 62, semantic: 14, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Physical Intelligence", domain: "physicalintelligence.company", category: "agents", score: 66, semantic: 16, jsonLd: 14, llmsTxt: 10, citability: 14, speed: 12 },
  { name: "Skild AI", domain: "skild.ai", category: "agents", score: 49, semantic: 13, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 10 },
  { name: "Covariant", domain: "covariant.ai", category: "agents", score: 37, semantic: 9, jsonLd: 7, llmsTxt: 6, citability: 8, speed: 7 },
  { name: "GitHub Copilot", domain: "github.com", category: "devtools", score: 88, semantic: 23, jsonLd: 18, llmsTxt: 12, citability: 16, speed: 19 },
  { name: "Sourcegraph Cody", domain: "sourcegraph.com", category: "devtools", score: 72, semantic: 17, jsonLd: 15, llmsTxt: 10, citability: 15, speed: 15 },
  { name: "JetBrains AI", domain: "jetbrains.com", category: "devtools", score: 95, semantic: 25, jsonLd: 18, llmsTxt: 15, citability: 18, speed: 19 },
  { name: "Windsurf", domain: "windsurf.com", category: "devtools", score: 74, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 14 },
  { name: "Cline", domain: "cline.bot", category: "devtools", score: 61, semantic: 14, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 12 },
  { name: "Aider", domain: "aider.chat", category: "devtools", score: 78, semantic: 18, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 14 },
  { name: "Continue", domain: "continue.dev", category: "devtools", score: 69, semantic: 16, jsonLd: 15, llmsTxt: 9, citability: 15, speed: 14 },
  { name: "Pieces", domain: "pieces.app", category: "devtools", score: 77, semantic: 18, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 16 },
  { name: "Warp", domain: "warp.dev", category: "devtools", score: 69, semantic: 17, jsonLd: 13, llmsTxt: 11, citability: 15, speed: 13 },
  { name: "Zed", domain: "zed.dev", category: "devtools", score: 79, semantic: 20, jsonLd: 15, llmsTxt: 12, citability: 15, speed: 17 },
  { name: "Lovable", domain: "lovable.dev", category: "devtools", score: 64, semantic: 15, jsonLd: 13, llmsTxt: 9, citability: 14, speed: 13 },
  { name: "Bolt.new", domain: "bolt.new", category: "devtools", score: 61, semantic: 16, jsonLd: 13, llmsTxt: 8, citability: 11, speed: 13 },
  { name: "v0", domain: "v0.dev", category: "devtools", score: 89, semantic: 23, jsonLd: 16, llmsTxt: 13, citability: 20, speed: 17 },
  { name: "Tempo Labs", domain: "tempolabs.ai", category: "devtools", score: 57, semantic: 13, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 12 },
  { name: "Create.xyz", domain: "create.xyz", category: "devtools", score: 75, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 15 },
  { name: "Webstudio", domain: "webstudio.is", category: "devtools", score: 67, semantic: 16, jsonLd: 14, llmsTxt: 9, citability: 14, speed: 14 },
  { name: "Builder.io", domain: "builder.io", category: "devtools", score: 78, semantic: 19, jsonLd: 15, llmsTxt: 13, citability: 17, speed: 14 },
  { name: "Plasmic", domain: "plasmic.app", category: "devtools", score: 73, semantic: 20, jsonLd: 16, llmsTxt: 10, citability: 14, speed: 13 },
  { name: "Framer AI", domain: "framer.com", category: "devtools", score: 98, semantic: 24, jsonLd: 20, llmsTxt: 14, citability: 20, speed: 20 },
  { name: "Wix Studio", domain: "wix.com", category: "devtools", score: 88, semantic: 20, jsonLd: 16, llmsTxt: 14, citability: 19, speed: 19 },
  { name: "Webflow AI", domain: "webflow.com", category: "devtools", score: 65, semantic: 17, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 13 },
  { name: "Glide AI", domain: "glide.com", category: "devtools", score: 60, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 11, speed: 13 },
  { name: "Softr", domain: "softr.io", category: "devtools", score: 81, semantic: 21, jsonLd: 15, llmsTxt: 12, citability: 15, speed: 18 },
  { name: "Retool", domain: "retool.com", category: "devtools", score: 63, semantic: 17, jsonLd: 12, llmsTxt: 11, citability: 12, speed: 11 },
  { name: "Appsmith", domain: "appsmith.com", category: "devtools", score: 70, semantic: 16, jsonLd: 15, llmsTxt: 10, citability: 14, speed: 15 },
  { name: "Tooljet", domain: "tooljet.com", category: "devtools", score: 72, semantic: 20, jsonLd: 14, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Budibase", domain: "budibase.com", category: "devtools", score: 51, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Mage", domain: "mage.ai", category: "devtools", score: 49, semantic: 14, jsonLd: 9, llmsTxt: 8, citability: 9, speed: 9 },
  { name: "Dagster", domain: "dagster.io", category: "devtools", score: 90, semantic: 21, jsonLd: 19, llmsTxt: 13, citability: 19, speed: 18 },
  { name: "Prefect", domain: "prefect.io", category: "devtools", score: 82, semantic: 19, jsonLd: 15, llmsTxt: 13, citability: 17, speed: 18 },
  { name: "Airflow", domain: "airflow.apache.org", category: "devtools", score: 61, semantic: 14, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 12 },
  { name: "Flyte", domain: "flyte.org", category: "devtools", score: 58, semantic: 14, jsonLd: 11, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "ZenML", domain: "zenml.io", category: "devtools", score: 85, semantic: 24, jsonLd: 15, llmsTxt: 13, citability: 17, speed: 16 },
  { name: "Metaflow", domain: "metaflow.org", category: "devtools", score: 91, semantic: 24, jsonLd: 19, llmsTxt: 13, citability: 17, speed: 18 },
  { name: "Weights & Biases", domain: "wandb.ai", category: "devtools", score: 50, semantic: 12, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 10 },
  { name: "Comet", domain: "comet.com", category: "devtools", score: 67, semantic: 15, jsonLd: 12, llmsTxt: 11, citability: 14, speed: 15 },
  { name: "MLflow", domain: "mlflow.org", category: "devtools", score: 74, semantic: 20, jsonLd: 14, llmsTxt: 11, citability: 14, speed: 15 },
  { name: "Neptune", domain: "neptune.ai", category: "devtools", score: 59, semantic: 15, jsonLd: 12, llmsTxt: 8, citability: 13, speed: 11 },
  { name: "Aim", domain: "aimstack.io", category: "devtools", score: 89, semantic: 23, jsonLd: 18, llmsTxt: 15, citability: 16, speed: 17 },
  { name: "ClearML", domain: "clear.ml", category: "devtools", score: 73, semantic: 17, jsonLd: 16, llmsTxt: 10, citability: 16, speed: 14 },
  { name: "Hopsworks", domain: "hopsworks.ai", category: "devtools", score: 84, semantic: 23, jsonLd: 17, llmsTxt: 11, citability: 17, speed: 16 },
  { name: "Tecton", domain: "tecton.ai", category: "devtools", score: 85, semantic: 19, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 18 },
  { name: "Featureform", domain: "featureform.com", category: "devtools", score: 60, semantic: 15, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 11 },
  { name: "LangSmith", domain: "smith.langchain.com", category: "devtools", score: 80, semantic: 18, jsonLd: 17, llmsTxt: 11, citability: 17, speed: 17 },
  { name: "LangGraph", domain: "langgraph.dev", category: "devtools", score: 87, semantic: 23, jsonLd: 17, llmsTxt: 12, citability: 17, speed: 18 },
  { name: "LangFuse", domain: "langfuse.com", category: "devtools", score: 62, semantic: 16, jsonLd: 11, llmsTxt: 10, citability: 11, speed: 14 },
  { name: "Arize", domain: "arize.com", category: "devtools", score: 64, semantic: 17, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "Phoenix", domain: "phoenix.arize.com", category: "devtools", score: 59, semantic: 15, jsonLd: 11, llmsTxt: 10, citability: 11, speed: 12 },
  { name: "Galileo", domain: "rungalileo.io", category: "devtools", score: 57, semantic: 13, jsonLd: 11, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "TruEra", domain: "truera.com", category: "devtools", score: 61, semantic: 14, jsonLd: 13, llmsTxt: 8, citability: 13, speed: 13 },
  { name: "WhyLabs", domain: "whylabs.ai", category: "devtools", score: 83, semantic: 19, jsonLd: 17, llmsTxt: 14, citability: 17, speed: 16 },
  { name: "Fiddler", domain: "fiddler.ai", category: "devtools", score: 57, semantic: 16, jsonLd: 12, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Patronus", domain: "patronus.ai", category: "devtools", score: 67, semantic: 18, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 12 },
  { name: "Braintrust", domain: "braintrust.dev", category: "devtools", score: 79, semantic: 18, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 18 },
  { name: "PromptLayer", domain: "promptlayer.com", category: "devtools", score: 90, semantic: 24, jsonLd: 16, llmsTxt: 14, citability: 18, speed: 18 },
  { name: "Humanloop", domain: "humanloop.com", category: "devtools", score: 64, semantic: 18, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 12 },
  { name: "Confident AI", domain: "confident-ai.com", category: "devtools", score: 92, semantic: 22, jsonLd: 19, llmsTxt: 13, citability: 19, speed: 19 },
  { name: "Comet Opik", domain: "comet.com/opik", category: "devtools", score: 53, semantic: 14, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 11 },
  { name: "Athina", domain: "athina.ai", category: "devtools", score: 67, semantic: 18, jsonLd: 13, llmsTxt: 9, citability: 13, speed: 14 },
  { name: "Promptfoo", domain: "promptfoo.dev", category: "devtools", score: 51, semantic: 11, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 11 },
  { name: "Inspect AI", domain: "inspect.ai-safety-institute.org.uk", category: "devtools", score: 83, semantic: 21, jsonLd: 17, llmsTxt: 14, citability: 15, speed: 16 },
  { name: "Lakera", domain: "lakera.ai", category: "devtools", score: 58, semantic: 14, jsonLd: 11, llmsTxt: 9, citability: 12, speed: 12 },
  { name: "Robust Intelligence", domain: "robustintelligence.com", category: "devtools", score: 88, semantic: 21, jsonLd: 19, llmsTxt: 12, citability: 18, speed: 18 },
  { name: "Protect AI", domain: "protectai.com", category: "devtools", score: 91, semantic: 25, jsonLd: 17, llmsTxt: 15, citability: 17, speed: 17 },
  { name: "Pillar Security", domain: "pillar.security", category: "devtools", score: 76, semantic: 18, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 15 },
  { name: "Prompt Security", domain: "prompt.security", category: "devtools", score: 77, semantic: 18, jsonLd: 14, llmsTxt: 13, citability: 17, speed: 15 },
  { name: "HiddenLayer", domain: "hiddenlayer.com", category: "devtools", score: 50, semantic: 14, jsonLd: 9, llmsTxt: 8, citability: 10, speed: 9 },
  { name: "Snyk", domain: "snyk.io", category: "devtools", score: 83, semantic: 23, jsonLd: 16, llmsTxt: 11, citability: 16, speed: 17 },
  { name: "Semgrep", domain: "semgrep.dev", category: "devtools", score: 53, semantic: 12, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Sentry", domain: "sentry.io", category: "devtools", score: 79, semantic: 21, jsonLd: 16, llmsTxt: 11, citability: 15, speed: 16 },
  { name: "Datadog", domain: "datadoghq.com", category: "devtools", score: 77, semantic: 20, jsonLd: 14, llmsTxt: 12, citability: 14, speed: 17 },
  { name: "Honeycomb", domain: "honeycomb.io", category: "devtools", score: 64, semantic: 15, jsonLd: 12, llmsTxt: 10, citability: 14, speed: 13 },
  { name: "Grafana", domain: "grafana.com", category: "devtools", score: 94, semantic: 25, jsonLd: 20, llmsTxt: 13, citability: 18, speed: 18 },
  { name: "PostHog", domain: "posthog.com", category: "devtools", score: 68, semantic: 18, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 13 },
  { name: "Amplitude", domain: "amplitude.com", category: "devtools", score: 88, semantic: 20, jsonLd: 17, llmsTxt: 15, citability: 19, speed: 17 },
  { name: "Mixpanel", domain: "mixpanel.com", category: "devtools", score: 79, semantic: 21, jsonLd: 16, llmsTxt: 11, citability: 15, speed: 16 },
  { name: "Segment", domain: "segment.com", category: "devtools", score: 71, semantic: 18, jsonLd: 13, llmsTxt: 11, citability: 13, speed: 16 },
  { name: "Plain", domain: "plain.com", category: "devtools", score: 52, semantic: 12, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 11 },
  { name: "Linear", domain: "linear.app", category: "devtools", score: 90, semantic: 23, jsonLd: 19, llmsTxt: 12, citability: 16, speed: 20 },
  { name: "Height", domain: "height.app", category: "devtools", score: 60, semantic: 17, jsonLd: 11, llmsTxt: 10, citability: 11, speed: 11 },
  { name: "Raycast", domain: "raycast.com", category: "devtools", score: 89, semantic: 24, jsonLd: 17, llmsTxt: 15, citability: 17, speed: 16 },
  { name: "Arc", domain: "arc.codes", category: "devtools", score: 65, semantic: 18, jsonLd: 12, llmsTxt: 10, citability: 13, speed: 12 },
  { name: "Wasp", domain: "wasp-lang.dev", category: "devtools", score: 73, semantic: 18, jsonLd: 16, llmsTxt: 10, citability: 16, speed: 13 },
  { name: "Encore", domain: "encore.dev", category: "devtools", score: 63, semantic: 15, jsonLd: 11, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Nitric", domain: "nitric.io", category: "devtools", score: 53, semantic: 14, jsonLd: 11, llmsTxt: 7, citability: 10, speed: 11 },
  { name: "Inngest", domain: "inngest.com", category: "devtools", score: 87, semantic: 20, jsonLd: 18, llmsTxt: 12, citability: 18, speed: 19 },
  { name: "Trigger.dev", domain: "trigger.dev", category: "devtools", score: 69, semantic: 15, jsonLd: 15, llmsTxt: 10, citability: 14, speed: 15 },
  { name: "Defer", domain: "defer.run", category: "devtools", score: 90, semantic: 24, jsonLd: 17, llmsTxt: 15, citability: 17, speed: 17 },
  { name: "Temporal", domain: "temporal.io", category: "devtools", score: 54, semantic: 13, jsonLd: 10, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Hatchet", domain: "hatchet.run", category: "devtools", score: 74, semantic: 17, jsonLd: 16, llmsTxt: 11, citability: 15, speed: 15 },
  { name: "Mastra", domain: "mastra.ai", category: "devtools", score: 81, semantic: 18, jsonLd: 18, llmsTxt: 12, citability: 17, speed: 16 },
  { name: "Inkeep", domain: "inkeep.com", category: "devtools", score: 57, semantic: 15, jsonLd: 11, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "Mendable", domain: "mendable.ai", category: "devtools", score: 94, semantic: 21, jsonLd: 20, llmsTxt: 14, citability: 20, speed: 19 },
  { name: "Kapa.ai", domain: "kapa.ai", category: "devtools", score: 65, semantic: 17, jsonLd: 14, llmsTxt: 9, citability: 12, speed: 13 },
  { name: "Firecrawl", domain: "firecrawl.dev", category: "devtools", score: 75, semantic: 20, jsonLd: 16, llmsTxt: 10, citability: 13, speed: 16 },
  { name: "Apify", domain: "apify.com", category: "devtools", score: 75, semantic: 17, jsonLd: 15, llmsTxt: 12, citability: 16, speed: 15 },
  { name: "Browserbase", domain: "browserbase.com", category: "devtools", score: 74, semantic: 20, jsonLd: 16, llmsTxt: 11, citability: 14, speed: 13 },
  { name: "Browserless", domain: "browserless.io", category: "devtools", score: 59, semantic: 16, jsonLd: 11, llmsTxt: 10, citability: 11, speed: 11 },
  { name: "ScrapingBee", domain: "scrapingbee.com", category: "devtools", score: 59, semantic: 14, jsonLd: 12, llmsTxt: 8, citability: 13, speed: 12 },
  { name: "Bright Data", domain: "brightdata.com", category: "devtools", score: 81, semantic: 18, jsonLd: 15, llmsTxt: 13, citability: 17, speed: 18 },
  { name: "Stagehand", domain: "stagehand.dev", category: "devtools", score: 89, semantic: 23, jsonLd: 19, llmsTxt: 12, citability: 16, speed: 19 },
  { name: "E2B", domain: "e2b.dev", category: "devtools", score: 49, semantic: 11, jsonLd: 9, llmsTxt: 8, citability: 11, speed: 10 },
  { name: "Daytona", domain: "daytona.io", category: "devtools", score: 52, semantic: 13, jsonLd: 10, llmsTxt: 8, citability: 10, speed: 11 },
  { name: "Coder", domain: "coder.com", category: "devtools", score: 64, semantic: 17, jsonLd: 13, llmsTxt: 9, citability: 11, speed: 14 },
  { name: "Gitpod", domain: "gitpod.io", category: "devtools", score: 61, semantic: 15, jsonLd: 12, llmsTxt: 10, citability: 13, speed: 11 },
  { name: "Codesandbox", domain: "codesandbox.io", category: "devtools", score: 85, semantic: 22, jsonLd: 18, llmsTxt: 11, citability: 15, speed: 19 },
  { name: "StackBlitz", domain: "stackblitz.com", category: "devtools", score: 65, semantic: 17, jsonLd: 12, llmsTxt: 10, citability: 12, speed: 14 },
  { name: "Convex Auth", domain: "labs.convex.dev", category: "devtools", score: 68, semantic: 16, jsonLd: 15, llmsTxt: 10, citability: 13, speed: 14 },
  { name: "Clerk", domain: "clerk.com", category: "devtools", score: 57, semantic: 13, jsonLd: 13, llmsTxt: 9, citability: 11, speed: 11 },
  { name: "WorkOS", domain: "workos.com", category: "devtools", score: 51, semantic: 12, jsonLd: 11, llmsTxt: 7, citability: 11, speed: 10 },
  { name: "Auth0", domain: "auth0.com", category: "devtools", score: 62, semantic: 17, jsonLd: 12, llmsTxt: 8, citability: 12, speed: 13 },
  { name: "Stytch", domain: "stytch.com", category: "devtools", score: 60, semantic: 15, jsonLd: 13, llmsTxt: 8, citability: 11, speed: 13 },
  { name: "Resend", domain: "resend.com", category: "devtools", score: 87, semantic: 22, jsonLd: 18, llmsTxt: 12, citability: 16, speed: 19 },
  { name: "Loops", domain: "loops.so", category: "devtools", score: 68, semantic: 18, jsonLd: 14, llmsTxt: 11, citability: 12, speed: 13 },
  { name: "Postmark", domain: "postmarkapp.com", category: "devtools", score: 93, semantic: 24, jsonLd: 20, llmsTxt: 13, citability: 18, speed: 18 },
];

export function getLeaderboard(category?: LeaderboardCategory): LeaderboardEntry[] {
  const filtered = category ? LEADERBOARD.filter((e) => e.category === category) : LEADERBOARD;
  return [...filtered]
    .sort((a, b) => b.score - a.score)
    .map((e, i) => ({ ...e, rank: i + 1 }));
}

export function countByCategory(): Record<LeaderboardCategory, number> {
  return {
    infra: LEADERBOARD.filter((e) => e.category === "infra").length,
    models: LEADERBOARD.filter((e) => e.category === "models").length,
    agents: LEADERBOARD.filter((e) => e.category === "agents").length,
    devtools: LEADERBOARD.filter((e) => e.category === "devtools").length,
  };
}
