// Static blog data. Add new posts here — they'll appear at /blog
// and at /blog/<slug> automatically.

export interface BlogPost {
  slug: string;
  title: string;
  description: string; // used as meta description + listing excerpt
  publishedAt: string; // ISO date
  readingMinutes: number;
  tags: string[];
  // Body is plain HTML-ish JSX. Keep it simple — paragraphs as strings, with
  // optional headings prefixed by "## " and lists prefixed by "- ".
  body: string;
}

export const POSTS: BlogPost[] = [
  {
    slug: "how-to-make-a-website-ai-readable",
    title: "How to Make a Website AI-Readable: A 2026 Step-by-Step",
    description:
      "A practical, code-level walkthrough for making your site readable by ChatGPT, Perplexity, and Claude. Semantic HTML, JSON-LD, llms.txt, robots — in the order they matter.",
    publishedAt: "2026-05-21",
    readingMinutes: 9,
    tags: ["ai readable website", "geo", "llm seo", "agent native"],
    body: `If you want ChatGPT, Perplexity, and Claude to cite your site, you have to make it readable to them first. "Readable" doesn't mean keyword-stuffed — it means parseable without a browser, structured without ambiguity, and explicit about what each page is. Here's the order to do it in.\n\n## Step 1 — Server-render the HTML\n\nLLM crawlers don't run your JavaScript. If your homepage is a React shell that hydrates with content, agents see an empty div. Use SSR, SSG, or a framework that ships HTML on first byte. Test with: curl -sL https://yoursite.com | grep -i "your headline". If your headline isn't in the output, no agent will ever read it.\n\n## Step 2 — Use semantic HTML\n\nReplace div soup with real landmarks: header, nav, main, article, section, footer. Use one h1 per page, then h2/h3 in order. Lists are ul/ol. Quotes are blockquote. Forms have labels. This isn't pedantry — it's the only signal an LLM has about the shape of your page.\n\n## Step 3 — Add JSON-LD on every page type\n\nMinimum viable set:\n\n- Organization on the root layout — name, url, logo, sameAs links\n- WebSite with a SearchAction if you have search\n- Article on every blog post — headline, datePublished, author, image\n- Product or Service on commercial pages — name, description, offers\n- FAQPage where you have Q&A\n- BreadcrumbList on deep routes\n\nValidate with Google's Rich Results test. Invalid JSON-LD is worse than none — it gets silently ignored.\n\n## Step 4 — Ship a /llms.txt\n\nA markdown file at the root summarizing the site: a one-line tagline as a blockquote, then ## sections for Services, Pricing, Pages, Contact. Pricing in plain numbers. Every public URL listed. No HTML, no JS, no images. Serve it as text/plain.\n\n## Step 5 — Allow the AI crawlers explicitly in robots.txt\n\nNamed Allow directives for GPTBot, OAI-SearchBot, ChatGPT-User, PerplexityBot, ClaudeBot, anthropic-ai, Google-Extended. Default Allow: / isn't enough — some bots honor only their named block.\n\n## Step 6 — Keep your sitemap fresh\n\nOne entry per public route, with accurate lastmod. Agents use sitemap to discover, llms.txt to summarize, and crawled HTML to verify. All three have to agree.\n\n## Step 7 — Audit and re-audit\n\nFetch any page with curl. Read the raw HTML. Can you answer "what is this page about, what does it offer, what does it cost?" without rendering anything? If yes, an agent can too. If not, work backwards through the steps above.\n\n## The shortcut: score it\n\nRun your URL through our free Agent Readability Checker at /check. It crawls the page the same way LLMs do and gives you a weighted score across all of the above, with the exact fixes prioritized.`,
  },
  {
    slug: "generative-engine-optimization-for-ai-startups",
    title: "Generative Engine Optimization (GEO) for AI Startups",
    description:
      "How AI-native founders should think about being cited by ChatGPT, Perplexity, and Claude — the channel-by-channel playbook for earning LLM citations.",
    publishedAt: "2026-05-19",
    readingMinutes: 8,
    tags: ["generative engine optimization", "geo", "ai startup marketing", "llm citation"],
    body: `Generative Engine Optimization (GEO) is the practice of getting your brand cited in the answers AI assistants give to user questions. It's adjacent to SEO but operates on a different ranking signal: not links, but consensus. Here's the playbook for AI startups specifically — the cohort with the highest leverage and the worst hygiene.\n\n## What GEO actually optimizes for\n\nClassic SEO optimizes for a click. GEO optimizes for a sentence in an LLM response. The unit isn't a ranking position — it's a citation footnote. You win GEO by being the source the model trusts when summarizing your category.\n\n## The four GEO surfaces\n\n1. Your own site — has to be machine-parseable (semantic HTML, JSON-LD, llms.txt). Without this, even high-authority links won't translate to citations.\n2. Developer communities — GitHub README files, MCP server registries, Hacker News threads, dev.to posts. LLM training corpora pull heavily from these.\n3. Independent directories — There's an AI for That, Futurepedia, AI tool roundups. These show up disproportionately in retrieval-augmented answers.\n4. First-party docs — Open-source repos, API references, public changelogs. These are dense, recently-updated, and trusted by name.\n\n## The AI-startup advantage\n\nYour customers are already technical. Your product naturally produces docs, SDKs, and CLIs. Every npm package, every GitHub stars page, every MCP server you publish becomes training data and retrieval context. The work isn't unnatural — it's productizing the artifacts you already generate.\n\n## The AI-startup mistakes\n\n- A homepage that's pure React shell with no SSR — the bot sees nothing\n- A "Product" page hidden behind a waitlist with no text describing what it does\n- Pricing locked in a "Contact us" form — no model will ever cite a price it can't read\n- A blog with one launch post from 18 months ago — no signal of recency\n\n## The 90-day GEO sprint\n\nWeek 1-2: ship semantic HTML, JSON-LD, llms.txt, and a sitemap. Audit with our checker at /check.\n\nWeek 3-4: publish 3 long-form posts targeting "what is X" queries in your category. Plain text, real examples, opinionated takes.\n\nWeek 5-8: open-source one tool — a TypeScript SDK, an MCP server, an eval harness. Document it like a product, not a side project.\n\nWeek 9-12: submit to the 5 directories your category is searched on. Pitch one podcast and one dev newsletter.\n\nThen measure. Search your category in ChatGPT, Perplexity, and Claude monthly. The first time your brand appears unbidden, you've won a citation. Compound from there.\n\n## What this is not\n\nGEO is not prompt injection, not cloaking, not stuffing llms.txt with marketing copy. Models are getting better at filtering manipulation and worse at tolerating it. The boring answer — structured, factual, well-attributed content — is the only one that compounds.`,
  },
  {
    slug: "best-json-ld-schema-for-saas",
    title: "Best JSON-LD Schema for SaaS: Copy-Paste Templates",
    description:
      "The exact JSON-LD blocks every SaaS site should ship — Organization, SoftwareApplication, Product, FAQPage, BreadcrumbList — with copy-paste examples.",
    publishedAt: "2026-05-17",
    readingMinutes: 7,
    tags: ["json-ld saas", "structured data", "schema.org", "saas seo"],
    body: `JSON-LD is the structured-data format Google, Bing, and every major LLM expects. For SaaS, the right schemas are non-obvious: you're not an e-commerce store, you're not a publisher, but you're not nothing either. Here are the five schemas every SaaS site should ship, with copy-paste templates.\n\n## 1. Organization — on every page (root layout)\n\nThis is your identity. Ship it once in the root layout. Use @type Organization with name, url, logo, and sameAs links to your Twitter, GitHub, and LinkedIn.\n\n## 2. SoftwareApplication — on your product/home page\n\nThe correct type for SaaS — better than generic Product. Use applicationCategory BusinessApplication, operatingSystem Web, and an Offer with price and priceCurrency. Add aggregateRating only if you have real reviews.\n\n## 3. Product or Service — on each pricing tier\n\nIf you sell distinct tiers (Starter, Growth, Enterprise), each is its own Product with its own Offer. This is what powers price citations in AI answers. Match the price exactly to what's visible on the page — Google deranks contradictions.\n\n## 4. FAQPage — on the FAQ route\n\nThe schema that punches above its weight. Rich-results-eligible on Google, frequently cited by LLMs. Each Q&A pair is a Question with an acceptedAnswer Answer.\n\n## 5. BreadcrumbList — on every deep route\n\nGives crawlers and LLMs your site hierarchy. Cheap, undervalued. Each ListItem has position, name, and item URL.\n\n## Mistakes that get your schema ignored\n\n- Putting JSON-LD inside an HTML comment or escaping the quotes wrong\n- Using @type values that aren't in schema.org\n- Listing a price that contradicts your pricing page\n- Shipping the same Organization block on a /not-found page with a different name\n\n## How to validate\n\nGoogle Rich Results Test flags invalid blocks. Schema.org's validator is stricter and catches type mismatches. Run both before shipping.\n\n## Where these compound\n\nClean structured data is the difference between getting cited as "a tool" and getting cited as "Acme — $29/mo SaaS for X." LLMs need the entity, the category, the price, and the URL. JSON-LD hands them all four in one parse.`,
  },
  {
    slug: "what-is-an-agent-native-website",
    title: "What Is an Agent-Native Website? A Definition for 2026",
    description:
      "Agent-native websites are built so AI agents — ChatGPT, Perplexity, Claude — can read, understand, and cite them. Here's the definition, the stack, and why it matters now.",
    publishedAt: "2026-05-20",
    readingMinutes: 7,
    tags: ["agent native website", "ai seo", "llm citation"],
    body: `An agent-native website is one engineered so AI agents — ChatGPT, Perplexity, Claude, Gemini — can parse it, understand it, and cite it back to users. It's the natural successor to "mobile-first" and "SEO-optimized." The audience expanded; the craft hasn't caught up.\n\n## The short definition\n\nAn agent-native website ships three things the average site doesn't:\n\n- **Semantic HTML** that describes meaning, not just layout — real headings, lists, articles, sections\n- **JSON-LD structured data** on every meaningful page — Organization, Article, Product, FAQPage, Service\n- **An /llms.txt file** that gives agents a clean, plain-text map of the site\n\nIf an LLM crawler can pull your page, identify the entity, and quote it without guessing — you're agent-native. If it has to render JavaScript, parse a div soup, and infer your pricing from a marketing paragraph — you're not.\n\n## Why this matters now\n\nReferral traffic patterns are shifting. ChatGPT, Perplexity, and Google's AI Overviews now answer questions inline instead of sending a click. The sites that get named in those answers are the ones agents can confidently cite. Citation is the new ranking.\n\nThis isn't speculative. Perplexity publishes its sources. ChatGPT links them when browsing. Claude cites them. Whether you show up in those citations depends almost entirely on how machine-readable your site is.\n\n## The agent-native stack\n\n- HTML: server-rendered, semantic, with a clear single H1 per page\n- Metadata: per-page title + description + OpenGraph, never one generic root tag\n- Structured data: JSON-LD for every entity type the page represents\n- /llms.txt: a markdown summary at the root, listing services, pricing, and key URLs\n- /robots.txt: explicit Allow for GPTBot, ClaudeBot, PerplexityBot, Google-Extended\n- Sitemap: accurate lastmod dates, every public route listed\n\n## What it isn't\n\nIt isn't a plugin. It isn't a template. It isn't keyword stuffing for robots. Agent-native sites read better for humans because the discipline that makes them legible to machines — clear hierarchy, plain language, structured facts — also makes them legible to readers.\n\n## How to check yours\n\nFetch your homepage with curl and read the raw HTML. If you can answer "what does this company do, what does it cost, and how do I contact them" without rendering JavaScript, an agent can too. If you can't, neither can ChatGPT.`,
  },
  {
    slug: "llms-txt-optimization-guide",
    title: "llms.txt Optimization: The Complete Guide for 2026",
    description:
      "How to write an /llms.txt file that AI agents actually use. Format, structure, what to include, and the mistakes that make agents skip your site.",
    publishedAt: "2026-05-18",
    readingMinutes: 8,
    tags: ["llms.txt optimization", "llms.txt", "ai seo"],
    body: `An /llms.txt file is a plain-text markdown summary of your site, served at the root, designed for large language models to read. Think of it as robots.txt for meaning instead of permissions. Done right, it's the single highest-leverage SEO file you'll ship in 2026.\n\n## The format\n\nllms.txt lives at https://yourdomain.com/llms.txt. It's markdown. It starts with an H1 (your site name) followed by a blockquote summary, then sections for About, Services, Pricing, Pages, and Contact. No HTML, no JavaScript, no images. Just structured text.\n\n## What to include\n\n- A blockquote summary under the H1 — agents quote this verbatim\n- Pricing in plain numbers — $2,400 not "starting at low four figures"\n- Every public URL — agents won't infer them from a sitemap\n- Contact + response time — turns citations into leads\n- A content license line — explicit permission for AI systems to cite you\n\n## What to leave out\n\n- Marketing fluff ("revolutionary," "synergy," "industry-leading")\n- Internal jargon and product codenames\n- Login URLs, admin paths, checkout success pages\n- Anything that contradicts your actual website — agents notice\n\n## Common mistakes\n\n1. Serving HTML instead of plain text — set Content-Type: text/plain or just ship a static file in /public\n2. Linking to a sitemap.xml and calling it done — sitemap is for crawlers, llms.txt is for understanding\n3. Forgetting to update it — stale pricing in llms.txt becomes wrong citations everywhere\n4. Hiding it behind auth or a CDN that requires JS — agents fetch with simple HTTP; if curl can't get it, neither can they\n\n## How to test it\n\nAsk ChatGPT: "Read https://yourdomain.com/llms.txt and summarize what this company does." If the summary matches your positioning, your file works. If it confabulates or pulls outdated info, fix the file.\n\n## The strategic point\n\nllms.txt isn't a ranking trick. It's a contract between your brand and the agents that increasingly mediate how customers find you. Sites that ship a clean llms.txt today are training the corpus of how their category gets described tomorrow.`,
  },
  {
    slug: "semantic-html-agency-why-it-matters",
    title: "Semantic HTML Is the New SEO: Why Agencies Are Rebuilding the Web",
    description:
      "Div soup is dying. Semantic HTML — real headings, articles, sections, lists — is what makes a site readable by humans, search engines, and AI agents alike.",
    publishedAt: "2026-05-15",
    readingMinutes: 6,
    tags: ["semantic website design", "semantic html", "agent native"],
    body: `Open the source of most marketing sites and you'll find a forest of div and span tags. It renders fine. It also tells crawlers and AI agents nothing about what's actually on the page. That's the bug semantic HTML fixes — and why a small wave of agencies are rebuilding sites around it.\n\n## What semantic HTML actually means\n\nIt's the difference between a styled div and an h1. Between a card div and an article. Between a wall of divs and a clear outline: header, nav, main, section, article, aside, footer.\n\nThose tags are not decoration. They're the API your site exposes to every non-human reader: screen readers, Google, ChatGPT, Perplexity. When the tags match the meaning, machines understand the page. When they don't, machines guess — and guesses don't get cited.\n\n## Why this is back\n\nFor a decade, semantic HTML was a nice-to-have because Google was good enough at inferring structure from CSS classes. AI agents are not. They tokenize raw HTML and look for landmarks. A page built on h1 → h2 → p is a clean signal. A page built on styled divs is noise.\n\nThe sites that get cited by ChatGPT, Perplexity, and Claude share a common trait: a parser can extract the structure without rendering. Semantic HTML is what makes that possible.\n\n## The semantic checklist\n\n- One h1 per page, matching the page topic\n- Headings nest correctly — no skipping from h1 to h4\n- main wraps the unique page content\n- Lists are ul or ol, not divs with bullets\n- Articles use article with a clear h2 headline\n- Forms have labels tied to inputs by for/id\n- Images have meaningful alt text — or empty alt if decorative\n\n## What an agency does differently\n\nA semantic-first agency builds the document outline before the visual design. The wireframe is an HTML tree, not a Figma frame. Tailwind classes go on top of the right element, not in place of it. The result reads as well in a browser's reader mode as it does in production.\n\nThis discipline is what separates an "agent-native" build from a pretty template. Both look fine. Only one gets cited.\n\n## The compounding return\n\nSemantic HTML pays off three times: accessibility scores rise, organic search picks up, and AI agents start naming you in answers. None of those are line items. All of them are leverage.`,
  },
  {
    slug: "startup-web-design-agency-what-to-look-for",
    title: "How to Pick a Startup Web Design Agency",
    description:
      "A founder's checklist for hiring a startup web design agency: scope, pricing, turnaround, and 5 red flags that signal scope creep.",
    publishedAt: "2026-05-12",
    readingMinutes: 6,
    tags: ["startup web design agency", "hiring", "founders"],
    body: `Most early-stage founders don't need a "branding partner." You need a site that converts, loads fast, and ships before your next investor update. Here's how to filter agencies for that reality.\n\n## The 3 questions that cut the shortlist in half\n\nBefore scheduling a single intro call, send these in an email:\n\n- What is your fixed price and turnaround for a 5-page marketing site?\n- Do you write custom code, or assemble templates in a page builder?\n- Who owns the codebase after launch?\n\nIf you get vague answers, hourly rates, or "it depends" — move on. Real productized agencies have a number and a date.\n\n## Pricing model matters more than the price\n\nHourly billing punishes you for changing your mind. Day-rate retainers punish you for being decisive. Fixed-price, scope-bounded work aligns incentives: the agency wants to ship fast, you know the bill upfront.\n\n## Red flags\n\n- A discovery phase longer than the build phase\n- No live design review until week 3\n- "We'll send a proposal next week" (next week becomes never)\n- Stock-template-looking portfolio with logo swaps\n- Refuses to commit to a launch date in writing\n\n## Green flags\n\n- Public portfolio with live URLs you can inspect\n- Lighthouse scores above 90 across the board\n- A written launch date in the SOW\n- Hands you a git repo, not a CMS login\n\n## What "48 hours" actually means\n\nA 48-hour delivery isn't a rushed build — it's a tightly scoped one. You bring brand assets and content; the agency brings a battle-tested component system. Anything outside that scope (custom illustrations, multi-language, complex CMS) gets quoted separately.\n\nIf your timeline is "this quarter," shop for monthly retainers. If your timeline is "before our launch tweet on Friday," shop productized.`,
  },
  {
    slug: "saas-website-design-conversion-essentials",
    title: "SaaS Website Design: 7 Sections That Convert",
    description:
      "A pragmatic anatomy of a high-converting SaaS website — what each section should do, what to cut, and the conversion benchmarks to beat.",
    publishedAt: "2026-05-08",
    readingMinutes: 7,
    tags: ["saas website design", "conversion", "landing pages"],
    body: `Most SaaS sites look the same because most SaaS sites get the same advice. Here's the stripped-down version: 7 sections, in order, with one job each.\n\n## 1. Hero — answer "what + who" in 3 seconds\n\nHeadline says what the product is. Subheadline says who it's for. Primary CTA goes to signup, not a demo form. If a visitor can't repeat your value prop after one scroll, the hero failed.\n\n## 2. Social proof bar — borrow credibility immediately\n\nLogos of customers, investors, or press. No testimonials yet — too early in the scroll. Greyscale, small, above the fold or right below it.\n\n## 3. The problem section — name the pain in their words\n\nOne sentence per pain point. If you're describing the persona's Monday morning, you're doing it right. If you're describing your features, restart.\n\n## 4. The product, shown not told\n\nAnnotated product screenshots or a short looping video. Real UI, real data — not Figma mockups. Each visual should map to a pain point from section 3.\n\n## 5. Features grid — but only 3-6 of them\n\nGroup features by outcome, not by module. "Ship faster" beats "CLI tool." Resist the urge to list everything; the changelog is for that.\n\n## 6. Pricing — visible, with a recommended tier\n\nHiding pricing behind "Contact sales" loses self-serve revenue. If you have to gate it, at least show starting price and what's included. Mark one tier as "Most popular" — it lifts conversion 10-30% by itself.\n\n## 7. Final CTA — single, large, unmistakable\n\nNo nav, no footer links, no "Or read our blog." One action: start trial / book demo / sign up. The footer comes after.\n\n## Benchmarks to beat\n\n- Time-to-first-meaningful-paint under 1.5s\n- Hero CTA click rate above 8%\n- Pricing-page-to-signup above 12%\n\nIf you're below any of these, the design is leaking money — not the ads.`,
  },
  {
    slug: "landing-page-design-service-vs-diy-builder",
    title: "Landing Page Service vs DIY Builder: When to Switch",
    description:
      "Webflow, Framer, and Squarespace are great — until they aren't. When DIY builders stop scaling and a landing page service pays for itself.",
    publishedAt: "2026-05-03",
    readingMinutes: 5,
    tags: ["landing page design service", "webflow", "framer", "diy"],
    body: `DIY builders are the right answer for a lot of stages. The problem is staying on them past the point where they cost you more than they save.\n\n## The honest case for DIY\n\nPre-revenue, pre-team, pre-traffic — Framer or Webflow lets you ship something today. Templates are fine. Iteration is free. Don't hire an agency to build your first landing page; you don't know what you want yet.\n\n## The signals it's time to switch\n\nYou're hitting the ceiling of DIY when:\n\n- You're paying $40-80/month per editor seat and have 3+ editors\n- Page load times are above 2.5s and you've already enabled every optimization\n- You need A/B testing the builder doesn't natively support\n- Your team spends 4+ hours per week wrestling the CMS instead of writing copy\n- You want analytics, experiments, or integrations the platform locks behind enterprise tiers\n- The brand has outgrown the template and every customization fights the editor\n\n## What a landing page design service gives you that DIY doesn't\n\nCustom code means: real performance budgets, no platform tax, full control over the DOM for SEO, and components built around your data — not your data forced into someone else's components.\n\nYou also get a designer who has shipped 50+ landing pages thinking about your funnel, instead of you guessing which template will convert.\n\n## The hybrid play\n\nKeep the marketing site on DIY for speed of iteration. Move the high-stakes conversion pages — pricing, signup, top-of-funnel ad landers — to custom code. That's where 80% of your revenue passes through, and where DIY's compromises cost the most.\n\nWhen the marketing site itself slows you down more than it speeds you up, migrate the whole thing.`,
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}

export function getAllPosts(): BlogPost[] {
  return [...POSTS].sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}
