/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as VsRouteImport } from './routes/vs'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SopRouteImport } from './routes/sop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as OutreachRouteImport } from './routes/outreach'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsRouteImport } from './routes/llms'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CliRouteImport } from './routes/cli'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CheckRouteImport } from './routes/check'
import { Route as BadgeRouteImport } from './routes/badge'
import { Route as AuthDotmdRouteImport } from './routes/auth[.]md'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ContentIndexRouteImport } from './routes/content.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VsCompetitorRouteImport } from './routes/vs.$competitor'
import { Route as VerifyIdRouteImport } from './routes/verify.$id'
import { Route as GuideGenerativeEngineOptimizationRouteImport } from './routes/guide.generative-engine-optimization'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DashboardScanRouteImport } from './routes/dashboard.scan'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardPublishRouteImport } from './routes/dashboard.publish'
import { Route as DashboardCitationRouteImport } from './routes/dashboard.citation'
import { Route as DashboardBadgeRouteImport } from './routes/dashboard.badge'
import { Route as ContentDraftsRouteImport } from './routes/content.drafts'
import { Route as ContentCalendarRouteImport } from './routes/content.calendar'
import { Route as ContentBriefsRouteImport } from './routes/content.briefs'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckReportRouteImport } from './routes/check.report'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog/rss[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BadgeChar123idChar125DotsvgRouteImport } from './routes/badge.{$id}[.]svg'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as DotwellKnownMcpDotjsonRouteImport } from './routes/[.]well-known.mcp[.]json'
import { Route as DotwellKnownJwksDotjsonRouteImport } from './routes/[.]well-known.jwks[.]json'
import { Route as DotwellKnownHttpMessageSignaturesDirectoryRouteImport } from './routes/[.]well-known.http-message-signatures-directory'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known.api-catalog'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ContentDraftsIdRouteImport } from './routes/content.drafts.$id'
import { Route as ApiPublicPingRouteImport } from './routes/api/public/ping'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicLeaderboardDotjsonRouteImport } from './routes/api/public/leaderboard[.]json'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known.mcp.server-card[.]json'
import { Route as DotwellKnownAgentSkillsIndexDotjsonRouteImport } from './routes/[.]well-known.agent-skills.index[.]json'
import { Route as DotwellKnownAgentSkillsGrowGeoScanDotmdRouteImport } from './routes/[.]well-known.agent-skills.grow-geo-scan[.]md'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWidgetEmbedDotjsRouteImport } from './routes/api/public/widget/embed[.]js'
import { Route as ApiPublicWidgetBadgeDotsvgRouteImport } from './routes/api/public/widget/badge[.]svg'
import { Route as ApiPublicV1SpecsRouteImport } from './routes/api/public/v1/specs'
import { Route as ApiPublicV1ReadinessRouteImport } from './routes/api/public/v1/readiness'
import { Route as ApiPublicV1PostsRouteImport } from './routes/api/public/v1/posts'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1LeadsRouteImport } from './routes/api/public/v1/leads'
import { Route as ApiPublicV1DocsRouteImport } from './routes/api/public/v1/docs'
import { Route as ApiPublicV1AnalyzeRouteImport } from './routes/api/public/v1/analyze'
import { Route as ApiPublicStatsOverviewRouteImport } from './routes/api/public/stats/overview'
import { Route as ApiPublicOauthTokenRouteImport } from './routes/api/public/oauth/token'
import { Route as ApiPublicHooksRunScheduledScansRouteImport } from './routes/api/public/hooks/run-scheduled-scans'
import { Route as ApiPublicHooksRescanLeaderboardRouteImport } from './routes/api/public/hooks/rescan-leaderboard'
import { Route as ApiPublicV1PostsSlugRouteImport } from './routes/api/public/v1/posts.$slug'
import { Route as ApiPublicV1AdminTableRouteImport } from './routes/api/public/v1/admin.$table'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const VsRoute = VsRouteImport.update({
  id: '/vs',
  path: '/vs',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SopRoute = SopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OutreachRoute = OutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsRoute = LlmsRouteImport.update({
  id: '/llms',
  path: '/llms',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CliRoute = CliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeRoute = BadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDotmdRoute = AuthDotmdRouteImport.update({
  id: '/auth.md',
  path: '/auth.md',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCompetitorRoute = VsCompetitorRouteImport.update({
  id: '/$competitor',
  path: '/$competitor',
  getParentRoute: () => VsRoute,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideGenerativeEngineOptimizationRoute =
  GuideGenerativeEngineOptimizationRouteImport.update({
    id: '/guide/generative-engine-optimization',
    path: '/guide/generative-engine-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScanRoute = DashboardScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPublishRoute = DashboardPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCitationRoute = DashboardCitationRouteImport.update({
  id: '/citation',
  path: '/citation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBadgeRoute = DashboardBadgeRouteImport.update({
  id: '/badge',
  path: '/badge',
  getParentRoute: () => DashboardRoute,
} as any)
const ContentDraftsRoute = ContentDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => ContentRoute,
} as any)
const ContentCalendarRoute = ContentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ContentRoute,
} as any)
const ContentBriefsRoute = ContentBriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => ContentRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckReportRoute = CheckReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => CheckRoute,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgeChar123idChar125DotsvgRoute =
  BadgeChar123idChar125DotsvgRouteImport.update({
    id: '/{$id}.svg',
    path: '/{$id}.svg',
    getParentRoute: () => BadgeRoute,
  } as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpDotjsonRoute = DotwellKnownMcpDotjsonRouteImport.update({
  id: '/.well-known/mcp.json',
  path: '/.well-known/mcp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownJwksDotjsonRoute = DotwellKnownJwksDotjsonRouteImport.update({
  id: '/.well-known/jwks.json',
  path: '/.well-known/jwks.json',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownHttpMessageSignaturesDirectoryRoute =
  DotwellKnownHttpMessageSignaturesDirectoryRouteImport.update({
    id: '/.well-known/http-message-signatures-directory',
    path: '/.well-known/http-message-signatures-directory',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentDraftsIdRoute = ContentDraftsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContentDraftsRoute,
} as any)
const ApiPublicPingRoute = ApiPublicPingRouteImport.update({
  id: '/api/public/ping',
  path: '/api/public/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeaderboardDotjsonRoute =
  ApiPublicLeaderboardDotjsonRouteImport.update({
    id: '/api/public/leaderboard.json',
    path: '/api/public/leaderboard.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsIndexDotjsonRoute =
  DotwellKnownAgentSkillsIndexDotjsonRouteImport.update({
    id: '/.well-known/agent-skills/index.json',
    path: '/.well-known/agent-skills/index.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentSkillsGrowGeoScanDotmdRoute =
  DotwellKnownAgentSkillsGrowGeoScanDotmdRouteImport.update({
    id: '/.well-known/agent-skills/grow-geo-scan.md',
    path: '/.well-known/agent-skills/grow-geo-scan.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetEmbedDotjsRoute =
  ApiPublicWidgetEmbedDotjsRouteImport.update({
    id: '/api/public/widget/embed.js',
    path: '/api/public/widget/embed.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWidgetBadgeDotsvgRoute =
  ApiPublicWidgetBadgeDotsvgRouteImport.update({
    id: '/api/public/widget/badge.svg',
    path: '/api/public/widget/badge.svg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1SpecsRoute = ApiPublicV1SpecsRouteImport.update({
  id: '/api/public/v1/specs',
  path: '/api/public/v1/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ReadinessRoute = ApiPublicV1ReadinessRouteImport.update({
  id: '/api/public/v1/readiness',
  path: '/api/public/v1/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PostsRoute = ApiPublicV1PostsRouteImport.update({
  id: '/api/public/v1/posts',
  path: '/api/public/v1/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1LeadsRoute = ApiPublicV1LeadsRouteImport.update({
  id: '/api/public/v1/leads',
  path: '/api/public/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DocsRoute = ApiPublicV1DocsRouteImport.update({
  id: '/api/public/v1/docs',
  path: '/api/public/v1/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AnalyzeRoute = ApiPublicV1AnalyzeRouteImport.update({
  id: '/api/public/v1/analyze',
  path: '/api/public/v1/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatsOverviewRoute = ApiPublicStatsOverviewRouteImport.update({
  id: '/api/public/stats/overview',
  path: '/api/public/stats/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthTokenRoute = ApiPublicOauthTokenRouteImport.update({
  id: '/api/public/oauth/token',
  path: '/api/public/oauth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunScheduledScansRoute =
  ApiPublicHooksRunScheduledScansRouteImport.update({
    id: '/api/public/hooks/run-scheduled-scans',
    path: '/api/public/hooks/run-scheduled-scans',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRescanLeaderboardRoute =
  ApiPublicHooksRescanLeaderboardRouteImport.update({
    id: '/api/public/hooks/rescan-leaderboard',
    path: '/api/public/hooks/rescan-leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1PostsSlugRoute = ApiPublicV1PostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicV1PostsRoute,
} as any)
const ApiPublicV1AdminTableRoute = ApiPublicV1AdminTableRouteImport.update({
  id: '/api/public/v1/admin/$table',
  path: '/api/public/v1/admin/$table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth.md': typeof AuthDotmdRoute
  '/badge': typeof BadgeRouteWithChildren
  '/check': typeof CheckRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/cli': typeof CliRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/llms': typeof LlmsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/playbook': typeof PlaybookRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs': typeof VsRouteWithChildren
  '/work': typeof WorkRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/badge/{$id}.svg': typeof BadgeChar123idChar125DotsvgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/check/report': typeof CheckReportRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/content/briefs': typeof ContentBriefsRoute
  '/content/calendar': typeof ContentCalendarRoute
  '/content/drafts': typeof ContentDraftsRouteWithChildren
  '/dashboard/badge': typeof DashboardBadgeRoute
  '/dashboard/citation': typeof DashboardCitationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/scan': typeof DashboardScanRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/generative-engine-optimization': typeof GuideGenerativeEngineOptimizationRoute
  '/verify/$id': typeof VerifyIdRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/blog/': typeof BlogIndexRoute
  '/content/': typeof ContentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.well-known/agent-skills/grow-geo-scan.md': typeof DotwellKnownAgentSkillsGrowGeoScanDotmdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/leaderboard.json': typeof ApiPublicLeaderboardDotjsonRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/content/drafts/$id': typeof ContentDraftsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/rescan-leaderboard': typeof ApiPublicHooksRescanLeaderboardRoute
  '/api/public/hooks/run-scheduled-scans': typeof ApiPublicHooksRunScheduledScansRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/stats/overview': typeof ApiPublicStatsOverviewRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRouteWithChildren
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
  '/api/public/v1/specs': typeof ApiPublicV1SpecsRoute
  '/api/public/widget/badge.svg': typeof ApiPublicWidgetBadgeDotsvgRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/$table': typeof ApiPublicV1AdminTableRoute
  '/api/public/v1/posts/$slug': typeof ApiPublicV1PostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth.md': typeof AuthDotmdRoute
  '/badge': typeof BadgeRouteWithChildren
  '/check': typeof CheckRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/cli': typeof CliRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/llms': typeof LlmsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/playbook': typeof PlaybookRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs': typeof VsRouteWithChildren
  '/work': typeof WorkRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/badge/{$id}.svg': typeof BadgeChar123idChar125DotsvgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/check/report': typeof CheckReportRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/content/briefs': typeof ContentBriefsRoute
  '/content/calendar': typeof ContentCalendarRoute
  '/content/drafts': typeof ContentDraftsRouteWithChildren
  '/dashboard/badge': typeof DashboardBadgeRoute
  '/dashboard/citation': typeof DashboardCitationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/scan': typeof DashboardScanRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/generative-engine-optimization': typeof GuideGenerativeEngineOptimizationRoute
  '/verify/$id': typeof VerifyIdRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/blog': typeof BlogIndexRoute
  '/content': typeof ContentIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/.well-known/agent-skills/grow-geo-scan.md': typeof DotwellKnownAgentSkillsGrowGeoScanDotmdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/leaderboard.json': typeof ApiPublicLeaderboardDotjsonRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/content/drafts/$id': typeof ContentDraftsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/rescan-leaderboard': typeof ApiPublicHooksRescanLeaderboardRoute
  '/api/public/hooks/run-scheduled-scans': typeof ApiPublicHooksRunScheduledScansRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/stats/overview': typeof ApiPublicStatsOverviewRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRouteWithChildren
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
  '/api/public/v1/specs': typeof ApiPublicV1SpecsRoute
  '/api/public/widget/badge.svg': typeof ApiPublicWidgetBadgeDotsvgRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/$table': typeof ApiPublicV1AdminTableRoute
  '/api/public/v1/posts/$slug': typeof ApiPublicV1PostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth.md': typeof AuthDotmdRoute
  '/badge': typeof BadgeRouteWithChildren
  '/check': typeof CheckRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/cli': typeof CliRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/leaderboard': typeof LeaderboardRoute
  '/llms': typeof LlmsRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/login': typeof LoginRoute
  '/outreach': typeof OutreachRoute
  '/playbook': typeof PlaybookRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/products': typeof ProductsRoute
  '/refund': typeof RefundRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sop': typeof SopRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vs': typeof VsRouteWithChildren
  '/work': typeof WorkRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/http-message-signatures-directory': typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  '/.well-known/jwks.json': typeof DotwellKnownJwksDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/badge/{$id}.svg': typeof BadgeChar123idChar125DotsvgRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/check/report': typeof CheckReportRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/content/briefs': typeof ContentBriefsRoute
  '/content/calendar': typeof ContentCalendarRoute
  '/content/drafts': typeof ContentDraftsRouteWithChildren
  '/dashboard/badge': typeof DashboardBadgeRoute
  '/dashboard/citation': typeof DashboardCitationRoute
  '/dashboard/publish': typeof DashboardPublishRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/scan': typeof DashboardScanRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/guide/generative-engine-optimization': typeof GuideGenerativeEngineOptimizationRoute
  '/verify/$id': typeof VerifyIdRoute
  '/vs/$competitor': typeof VsCompetitorRoute
  '/blog/': typeof BlogIndexRoute
  '/content/': typeof ContentIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/.well-known/agent-skills/grow-geo-scan.md': typeof DotwellKnownAgentSkillsGrowGeoScanDotmdRoute
  '/.well-known/agent-skills/index.json': typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/public/leaderboard.json': typeof ApiPublicLeaderboardDotjsonRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/ping': typeof ApiPublicPingRoute
  '/content/drafts/$id': typeof ContentDraftsIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/rescan-leaderboard': typeof ApiPublicHooksRescanLeaderboardRoute
  '/api/public/hooks/run-scheduled-scans': typeof ApiPublicHooksRunScheduledScansRoute
  '/api/public/oauth/token': typeof ApiPublicOauthTokenRoute
  '/api/public/stats/overview': typeof ApiPublicStatsOverviewRoute
  '/api/public/v1/analyze': typeof ApiPublicV1AnalyzeRoute
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/api/public/v1/posts': typeof ApiPublicV1PostsRouteWithChildren
  '/api/public/v1/readiness': typeof ApiPublicV1ReadinessRoute
  '/api/public/v1/specs': typeof ApiPublicV1SpecsRoute
  '/api/public/widget/badge.svg': typeof ApiPublicWidgetBadgeDotsvgRoute
  '/api/public/widget/embed.js': typeof ApiPublicWidgetEmbedDotjsRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/v1/admin/$table': typeof ApiPublicV1AdminTableRoute
  '/api/public/v1/posts/$slug': typeof ApiPublicV1PostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/auth.md'
    | '/badge'
    | '/check'
    | '/checkout'
    | '/cli'
    | '/contact'
    | '/content'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/leaderboard'
    | '/llms'
    | '/llms-full.txt'
    | '/login'
    | '/outreach'
    | '/playbook'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/products'
    | '/refund'
    | '/rss.xml'
    | '/services'
    | '/sitemap.xml'
    | '/sop'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/vs'
    | '/work'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/admin/leads'
    | '/admin/reviews'
    | '/badge/{$id}.svg'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/check/report'
    | '/checkout/success'
    | '/content/briefs'
    | '/content/calendar'
    | '/content/drafts'
    | '/dashboard/badge'
    | '/dashboard/citation'
    | '/dashboard/publish'
    | '/dashboard/reviews'
    | '/dashboard/scan'
    | '/email/unsubscribe'
    | '/guide/generative-engine-optimization'
    | '/verify/$id'
    | '/vs/$competitor'
    | '/blog/'
    | '/content/'
    | '/dashboard/'
    | '/.well-known/agent-skills/grow-geo-scan.md'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/leaderboard.json'
    | '/api/public/leads'
    | '/api/public/mcp'
    | '/api/public/ping'
    | '/content/drafts/$id'
    | '/lovable/email/suppression'
    | '/api/public/hooks/rescan-leaderboard'
    | '/api/public/hooks/run-scheduled-scans'
    | '/api/public/oauth/token'
    | '/api/public/stats/overview'
    | '/api/public/v1/analyze'
    | '/api/public/v1/docs'
    | '/api/public/v1/leads'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/posts'
    | '/api/public/v1/readiness'
    | '/api/public/v1/specs'
    | '/api/public/widget/badge.svg'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/v1/'
    | '/api/public/v1/admin/$table'
    | '/api/public/v1/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/auth.md'
    | '/badge'
    | '/check'
    | '/checkout'
    | '/cli'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/leaderboard'
    | '/llms'
    | '/llms-full.txt'
    | '/login'
    | '/outreach'
    | '/playbook'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/products'
    | '/refund'
    | '/rss.xml'
    | '/services'
    | '/sitemap.xml'
    | '/sop'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/vs'
    | '/work'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/admin/leads'
    | '/admin/reviews'
    | '/badge/{$id}.svg'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/check/report'
    | '/checkout/success'
    | '/content/briefs'
    | '/content/calendar'
    | '/content/drafts'
    | '/dashboard/badge'
    | '/dashboard/citation'
    | '/dashboard/publish'
    | '/dashboard/reviews'
    | '/dashboard/scan'
    | '/email/unsubscribe'
    | '/guide/generative-engine-optimization'
    | '/verify/$id'
    | '/vs/$competitor'
    | '/blog'
    | '/content'
    | '/dashboard'
    | '/.well-known/agent-skills/grow-geo-scan.md'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/leaderboard.json'
    | '/api/public/leads'
    | '/api/public/mcp'
    | '/api/public/ping'
    | '/content/drafts/$id'
    | '/lovable/email/suppression'
    | '/api/public/hooks/rescan-leaderboard'
    | '/api/public/hooks/run-scheduled-scans'
    | '/api/public/oauth/token'
    | '/api/public/stats/overview'
    | '/api/public/v1/analyze'
    | '/api/public/v1/docs'
    | '/api/public/v1/leads'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/posts'
    | '/api/public/v1/readiness'
    | '/api/public/v1/specs'
    | '/api/public/widget/badge.svg'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/v1'
    | '/api/public/v1/admin/$table'
    | '/api/public/v1/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/auth.md'
    | '/badge'
    | '/check'
    | '/checkout'
    | '/cli'
    | '/contact'
    | '/content'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/leaderboard'
    | '/llms'
    | '/llms-full.txt'
    | '/login'
    | '/outreach'
    | '/playbook'
    | '/pricing'
    | '/privacy'
    | '/process'
    | '/products'
    | '/refund'
    | '/rss.xml'
    | '/services'
    | '/sitemap.xml'
    | '/sop'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/vs'
    | '/work'
    | '/.well-known/api-catalog'
    | '/.well-known/http-message-signatures-directory'
    | '/.well-known/jwks.json'
    | '/.well-known/mcp.json'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/oauth-protected-resource'
    | '/admin/leads'
    | '/admin/reviews'
    | '/badge/{$id}.svg'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/check/report'
    | '/checkout/success'
    | '/content/briefs'
    | '/content/calendar'
    | '/content/drafts'
    | '/dashboard/badge'
    | '/dashboard/citation'
    | '/dashboard/publish'
    | '/dashboard/reviews'
    | '/dashboard/scan'
    | '/email/unsubscribe'
    | '/guide/generative-engine-optimization'
    | '/verify/$id'
    | '/vs/$competitor'
    | '/blog/'
    | '/content/'
    | '/dashboard/'
    | '/.well-known/agent-skills/grow-geo-scan.md'
    | '/.well-known/agent-skills/index.json'
    | '/.well-known/mcp/server-card.json'
    | '/api/public/leaderboard.json'
    | '/api/public/leads'
    | '/api/public/mcp'
    | '/api/public/ping'
    | '/content/drafts/$id'
    | '/lovable/email/suppression'
    | '/api/public/hooks/rescan-leaderboard'
    | '/api/public/hooks/run-scheduled-scans'
    | '/api/public/oauth/token'
    | '/api/public/stats/overview'
    | '/api/public/v1/analyze'
    | '/api/public/v1/docs'
    | '/api/public/v1/leads'
    | '/api/public/v1/openapi.json'
    | '/api/public/v1/posts'
    | '/api/public/v1/readiness'
    | '/api/public/v1/specs'
    | '/api/public/widget/badge.svg'
    | '/api/public/widget/embed.js'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/api/public/v1/'
    | '/api/public/v1/admin/$table'
    | '/api/public/v1/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthDotmdRoute: typeof AuthDotmdRoute
  BadgeRoute: typeof BadgeRouteWithChildren
  CheckRoute: typeof CheckRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CliRoute: typeof CliRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LlmsRoute: typeof LlmsRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LoginRoute: typeof LoginRoute
  OutreachRoute: typeof OutreachRoute
  PlaybookRoute: typeof PlaybookRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ProductsRoute: typeof ProductsRoute
  RefundRoute: typeof RefundRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SopRoute: typeof SopRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VsRoute: typeof VsRouteWithChildren
  WorkRoute: typeof WorkRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownHttpMessageSignaturesDirectoryRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRoute
  DotwellKnownJwksDotjsonRoute: typeof DotwellKnownJwksDotjsonRoute
  DotwellKnownMcpDotjsonRoute: typeof DotwellKnownMcpDotjsonRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GuideGenerativeEngineOptimizationRoute: typeof GuideGenerativeEngineOptimizationRoute
  VerifyIdRoute: typeof VerifyIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotwellKnownAgentSkillsGrowGeoScanDotmdRoute: typeof DotwellKnownAgentSkillsGrowGeoScanDotmdRoute
  DotwellKnownAgentSkillsIndexDotjsonRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiPublicLeaderboardDotjsonRoute: typeof ApiPublicLeaderboardDotjsonRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicPingRoute: typeof ApiPublicPingRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksRescanLeaderboardRoute: typeof ApiPublicHooksRescanLeaderboardRoute
  ApiPublicHooksRunScheduledScansRoute: typeof ApiPublicHooksRunScheduledScansRoute
  ApiPublicOauthTokenRoute: typeof ApiPublicOauthTokenRoute
  ApiPublicStatsOverviewRoute: typeof ApiPublicStatsOverviewRoute
  ApiPublicV1AnalyzeRoute: typeof ApiPublicV1AnalyzeRoute
  ApiPublicV1DocsRoute: typeof ApiPublicV1DocsRoute
  ApiPublicV1LeadsRoute: typeof ApiPublicV1LeadsRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  ApiPublicV1PostsRoute: typeof ApiPublicV1PostsRouteWithChildren
  ApiPublicV1ReadinessRoute: typeof ApiPublicV1ReadinessRoute
  ApiPublicV1SpecsRoute: typeof ApiPublicV1SpecsRoute
  ApiPublicWidgetBadgeDotsvgRoute: typeof ApiPublicWidgetBadgeDotsvgRoute
  ApiPublicWidgetEmbedDotjsRoute: typeof ApiPublicWidgetEmbedDotjsRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
  ApiPublicV1AdminTableRoute: typeof ApiPublicV1AdminTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs': {
      id: '/vs'
      path: '/vs'
      fullPath: '/vs'
      preLoaderRoute: typeof VsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sop': {
      id: '/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof SopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outreach': {
      id: '/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof OutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms': {
      id: '/llms'
      path: '/llms'
      fullPath: '/llms'
      preLoaderRoute: typeof LlmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli': {
      id: '/cli'
      path: '/cli'
      fullPath: '/cli'
      preLoaderRoute: typeof CliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge': {
      id: '/badge'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof BadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth.md': {
      id: '/auth.md'
      path: '/auth.md'
      fullPath: '/auth.md'
      preLoaderRoute: typeof AuthDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$competitor': {
      id: '/vs/$competitor'
      path: '/$competitor'
      fullPath: '/vs/$competitor'
      preLoaderRoute: typeof VsCompetitorRouteImport
      parentRoute: typeof VsRoute
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/generative-engine-optimization': {
      id: '/guide/generative-engine-optimization'
      path: '/guide/generative-engine-optimization'
      fullPath: '/guide/generative-engine-optimization'
      preLoaderRoute: typeof GuideGenerativeEngineOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scan': {
      id: '/dashboard/scan'
      path: '/scan'
      fullPath: '/dashboard/scan'
      preLoaderRoute: typeof DashboardScanRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/publish': {
      id: '/dashboard/publish'
      path: '/publish'
      fullPath: '/dashboard/publish'
      preLoaderRoute: typeof DashboardPublishRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/citation': {
      id: '/dashboard/citation'
      path: '/citation'
      fullPath: '/dashboard/citation'
      preLoaderRoute: typeof DashboardCitationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/badge': {
      id: '/dashboard/badge'
      path: '/badge'
      fullPath: '/dashboard/badge'
      preLoaderRoute: typeof DashboardBadgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/content/drafts': {
      id: '/content/drafts'
      path: '/drafts'
      fullPath: '/content/drafts'
      preLoaderRoute: typeof ContentDraftsRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/calendar': {
      id: '/content/calendar'
      path: '/calendar'
      fullPath: '/content/calendar'
      preLoaderRoute: typeof ContentCalendarRouteImport
      parentRoute: typeof ContentRoute
    }
    '/content/briefs': {
      id: '/content/briefs'
      path: '/briefs'
      fullPath: '/content/briefs'
      preLoaderRoute: typeof ContentBriefsRouteImport
      parentRoute: typeof ContentRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/check/report': {
      id: '/check/report'
      path: '/report'
      fullPath: '/check/report'
      preLoaderRoute: typeof CheckReportRouteImport
      parentRoute: typeof CheckRoute
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badge/{$id}.svg': {
      id: '/badge/{$id}.svg'
      path: '/{$id}.svg'
      fullPath: '/badge/{$id}.svg'
      preLoaderRoute: typeof BadgeChar123idChar125DotsvgRouteImport
      parentRoute: typeof BadgeRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp.json': {
      id: '/.well-known/mcp.json'
      path: '/.well-known/mcp.json'
      fullPath: '/.well-known/mcp.json'
      preLoaderRoute: typeof DotwellKnownMcpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/jwks.json': {
      id: '/.well-known/jwks.json'
      path: '/.well-known/jwks.json'
      fullPath: '/.well-known/jwks.json'
      preLoaderRoute: typeof DotwellKnownJwksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/http-message-signatures-directory': {
      id: '/.well-known/http-message-signatures-directory'
      path: '/.well-known/http-message-signatures-directory'
      fullPath: '/.well-known/http-message-signatures-directory'
      preLoaderRoute: typeof DotwellKnownHttpMessageSignaturesDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/drafts/$id': {
      id: '/content/drafts/$id'
      path: '/$id'
      fullPath: '/content/drafts/$id'
      preLoaderRoute: typeof ContentDraftsIdRouteImport
      parentRoute: typeof ContentDraftsRoute
    }
    '/api/public/ping': {
      id: '/api/public/ping'
      path: '/api/public/ping'
      fullPath: '/api/public/ping'
      preLoaderRoute: typeof ApiPublicPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leaderboard.json': {
      id: '/api/public/leaderboard.json'
      path: '/api/public/leaderboard.json'
      fullPath: '/api/public/leaderboard.json'
      preLoaderRoute: typeof ApiPublicLeaderboardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/index.json': {
      id: '/.well-known/agent-skills/index.json'
      path: '/.well-known/agent-skills/index.json'
      fullPath: '/.well-known/agent-skills/index.json'
      preLoaderRoute: typeof DotwellKnownAgentSkillsIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-skills/grow-geo-scan.md': {
      id: '/.well-known/agent-skills/grow-geo-scan.md'
      path: '/.well-known/agent-skills/grow-geo-scan.md'
      fullPath: '/.well-known/agent-skills/grow-geo-scan.md'
      preLoaderRoute: typeof DotwellKnownAgentSkillsGrowGeoScanDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/embed.js': {
      id: '/api/public/widget/embed.js'
      path: '/api/public/widget/embed.js'
      fullPath: '/api/public/widget/embed.js'
      preLoaderRoute: typeof ApiPublicWidgetEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget/badge.svg': {
      id: '/api/public/widget/badge.svg'
      path: '/api/public/widget/badge.svg'
      fullPath: '/api/public/widget/badge.svg'
      preLoaderRoute: typeof ApiPublicWidgetBadgeDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/specs': {
      id: '/api/public/v1/specs'
      path: '/api/public/v1/specs'
      fullPath: '/api/public/v1/specs'
      preLoaderRoute: typeof ApiPublicV1SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/readiness': {
      id: '/api/public/v1/readiness'
      path: '/api/public/v1/readiness'
      fullPath: '/api/public/v1/readiness'
      preLoaderRoute: typeof ApiPublicV1ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/posts': {
      id: '/api/public/v1/posts'
      path: '/api/public/v1/posts'
      fullPath: '/api/public/v1/posts'
      preLoaderRoute: typeof ApiPublicV1PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/leads': {
      id: '/api/public/v1/leads'
      path: '/api/public/v1/leads'
      fullPath: '/api/public/v1/leads'
      preLoaderRoute: typeof ApiPublicV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/docs': {
      id: '/api/public/v1/docs'
      path: '/api/public/v1/docs'
      fullPath: '/api/public/v1/docs'
      preLoaderRoute: typeof ApiPublicV1DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/analyze': {
      id: '/api/public/v1/analyze'
      path: '/api/public/v1/analyze'
      fullPath: '/api/public/v1/analyze'
      preLoaderRoute: typeof ApiPublicV1AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stats/overview': {
      id: '/api/public/stats/overview'
      path: '/api/public/stats/overview'
      fullPath: '/api/public/stats/overview'
      preLoaderRoute: typeof ApiPublicStatsOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/token': {
      id: '/api/public/oauth/token'
      path: '/api/public/oauth/token'
      fullPath: '/api/public/oauth/token'
      preLoaderRoute: typeof ApiPublicOauthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled-scans': {
      id: '/api/public/hooks/run-scheduled-scans'
      path: '/api/public/hooks/run-scheduled-scans'
      fullPath: '/api/public/hooks/run-scheduled-scans'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rescan-leaderboard': {
      id: '/api/public/hooks/rescan-leaderboard'
      path: '/api/public/hooks/rescan-leaderboard'
      fullPath: '/api/public/hooks/rescan-leaderboard'
      preLoaderRoute: typeof ApiPublicHooksRescanLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/posts/$slug': {
      id: '/api/public/v1/posts/$slug'
      path: '/$slug'
      fullPath: '/api/public/v1/posts/$slug'
      preLoaderRoute: typeof ApiPublicV1PostsSlugRouteImport
      parentRoute: typeof ApiPublicV1PostsRoute
    }
    '/api/public/v1/admin/$table': {
      id: '/api/public/v1/admin/$table'
      path: '/api/public/v1/admin/$table'
      fullPath: '/api/public/v1/admin/$table'
      preLoaderRoute: typeof ApiPublicV1AdminTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BadgeRouteChildren {
  BadgeChar123idChar125DotsvgRoute: typeof BadgeChar123idChar125DotsvgRoute
}

const BadgeRouteChildren: BadgeRouteChildren = {
  BadgeChar123idChar125DotsvgRoute: BadgeChar123idChar125DotsvgRoute,
}

const BadgeRouteWithChildren = BadgeRoute._addFileChildren(BadgeRouteChildren)

interface CheckRouteChildren {
  CheckReportRoute: typeof CheckReportRoute
}

const CheckRouteChildren: CheckRouteChildren = {
  CheckReportRoute: CheckReportRoute,
}

const CheckRouteWithChildren = CheckRoute._addFileChildren(CheckRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ContentDraftsRouteChildren {
  ContentDraftsIdRoute: typeof ContentDraftsIdRoute
}

const ContentDraftsRouteChildren: ContentDraftsRouteChildren = {
  ContentDraftsIdRoute: ContentDraftsIdRoute,
}

const ContentDraftsRouteWithChildren = ContentDraftsRoute._addFileChildren(
  ContentDraftsRouteChildren,
)

interface ContentRouteChildren {
  ContentBriefsRoute: typeof ContentBriefsRoute
  ContentCalendarRoute: typeof ContentCalendarRoute
  ContentDraftsRoute: typeof ContentDraftsRouteWithChildren
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentBriefsRoute: ContentBriefsRoute,
  ContentCalendarRoute: ContentCalendarRoute,
  ContentDraftsRoute: ContentDraftsRouteWithChildren,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface DashboardRouteChildren {
  DashboardBadgeRoute: typeof DashboardBadgeRoute
  DashboardCitationRoute: typeof DashboardCitationRoute
  DashboardPublishRoute: typeof DashboardPublishRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardScanRoute: typeof DashboardScanRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBadgeRoute: DashboardBadgeRoute,
  DashboardCitationRoute: DashboardCitationRoute,
  DashboardPublishRoute: DashboardPublishRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardScanRoute: DashboardScanRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface VsRouteChildren {
  VsCompetitorRoute: typeof VsCompetitorRoute
}

const VsRouteChildren: VsRouteChildren = {
  VsCompetitorRoute: VsCompetitorRoute,
}

const VsRouteWithChildren = VsRoute._addFileChildren(VsRouteChildren)

interface ApiPublicV1PostsRouteChildren {
  ApiPublicV1PostsSlugRoute: typeof ApiPublicV1PostsSlugRoute
}

const ApiPublicV1PostsRouteChildren: ApiPublicV1PostsRouteChildren = {
  ApiPublicV1PostsSlugRoute: ApiPublicV1PostsSlugRoute,
}

const ApiPublicV1PostsRouteWithChildren =
  ApiPublicV1PostsRoute._addFileChildren(ApiPublicV1PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthDotmdRoute: AuthDotmdRoute,
  BadgeRoute: BadgeRouteWithChildren,
  CheckRoute: CheckRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  CliRoute: CliRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  LeaderboardRoute: LeaderboardRoute,
  LlmsRoute: LlmsRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LoginRoute: LoginRoute,
  OutreachRoute: OutreachRoute,
  PlaybookRoute: PlaybookRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ProductsRoute: ProductsRoute,
  RefundRoute: RefundRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SopRoute: SopRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VsRoute: VsRouteWithChildren,
  WorkRoute: WorkRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownHttpMessageSignaturesDirectoryRoute:
    DotwellKnownHttpMessageSignaturesDirectoryRoute,
  DotwellKnownJwksDotjsonRoute: DotwellKnownJwksDotjsonRoute,
  DotwellKnownMcpDotjsonRoute: DotwellKnownMcpDotjsonRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GuideGenerativeEngineOptimizationRoute:
    GuideGenerativeEngineOptimizationRoute,
  VerifyIdRoute: VerifyIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotwellKnownAgentSkillsGrowGeoScanDotmdRoute:
    DotwellKnownAgentSkillsGrowGeoScanDotmdRoute,
  DotwellKnownAgentSkillsIndexDotjsonRoute:
    DotwellKnownAgentSkillsIndexDotjsonRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiPublicLeaderboardDotjsonRoute: ApiPublicLeaderboardDotjsonRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicPingRoute: ApiPublicPingRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksRescanLeaderboardRoute: ApiPublicHooksRescanLeaderboardRoute,
  ApiPublicHooksRunScheduledScansRoute: ApiPublicHooksRunScheduledScansRoute,
  ApiPublicOauthTokenRoute: ApiPublicOauthTokenRoute,
  ApiPublicStatsOverviewRoute: ApiPublicStatsOverviewRoute,
  ApiPublicV1AnalyzeRoute: ApiPublicV1AnalyzeRoute,
  ApiPublicV1DocsRoute: ApiPublicV1DocsRoute,
  ApiPublicV1LeadsRoute: ApiPublicV1LeadsRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  ApiPublicV1PostsRoute: ApiPublicV1PostsRouteWithChildren,
  ApiPublicV1ReadinessRoute: ApiPublicV1ReadinessRoute,
  ApiPublicV1SpecsRoute: ApiPublicV1SpecsRoute,
  ApiPublicWidgetBadgeDotsvgRoute: ApiPublicWidgetBadgeDotsvgRoute,
  ApiPublicWidgetEmbedDotjsRoute: ApiPublicWidgetEmbedDotjsRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
  ApiPublicV1AdminTableRoute: ApiPublicV1AdminTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
